INSERT INTO `role_tbl` (`role_id`, `name`) VALUES (NULL, '教員');
INSERT INTO `role_tbl` (`role_id`, `name`) VALUES (NULL, '学生');
INSERT INTO `role_tbl` (`role_id`, `name`) VALUES (NULL, '企業');
INSERT INTO `school_tbl` (`school_tbl`, `name`, `abbreviation`) VALUES (NULL, '麻生情報ビジネス専門学校', 'ABCC');
INSERT INTO `department_tbl` (`department_id`, `name`, `school_id`) VALUES (NULL, '情報工学科', '1');
INSERT INTO `class_tbl` (`class_id`, `name`, `department_id`, `admin_id`) VALUES (NULL, 'SD2A', '1', '2');
INSERT INTO `jobhunting_status_tbl` (`jobhunting_status_id`, `name`) VALUES (NULL, '進路決定済み');
INSERT INTO `student_tbl` (`student_id`, `password`, `student_no`, `name`, `mail`, `class_id`, `jobhunting_status_id`, `image`, `tel`, `address`, `year`, `c_trust`, `c_entrapment`, `c_objectivity`, `c_physicality`, `c_moodiness`, `c_persistence`, `c_regularity`, `c_competitiveness`, `c_selfesteem`, `c_prudence`, `c_bearishness`, `c_surroundings`, `c_science`, `c_society`, `c_psychology`, `c_art`, `c_positivity`, `c_cooperativeness`, `c_responsibility`, `c_reliability`, `c_leadership`, `c_empathy`, `c_emotional_stability`, `c_obedience`, `c_autonomy`, `c_moratorium`, `c_desire_success`, `c_affinity`, `c_seeking`, `c_manifestation`, `c_order`, `c_material`, `c_crisis_resistance`, `c_independence`, `c_control`, `c_workethic`, `c_active`, `c_enthusiasm`, `c_perseverance`, `c_responsibility2`, `c_decisive`, `c_leadership2`, `c_leader`, `c_selftrust`, `c_adjustment`, `c_negotiation`, `c_innovative`, `c_analysis`, `c_Insight`, `c_planning`, `c_expertise`, `c_utilization`, `c_general`, `c_mental`, `c_legwaist`, `c_concentration`, `c_standardization`, `c_range`, `c_established`, `c_typejudge`) VALUES (NULL, '387a0051226be0d20927b2c0bb46becd', '0000001', '西野直幸', 'nishino@s.asojuku.ac.jp', '1', '1', 'noimage.png', '1', '福岡市', '2022', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `admin_tbl` (`admin_id`, `name`, `mail`, `password`, `image`, `role_id`) VALUES
(NULL, '西野直幸', 'nishino@asojuku.ac.jp', '0b8b3f1d7f7dca255b216eb22ec576ab', '', 1);