INSERT INTO `role_tbl` (`role_id`, `name`) VALUES (NULL, '教員');
INSERT INTO `role_tbl` (`role_id`, `name`) VALUES (NULL, '学生');
INSERT INTO `role_tbl` (`role_id`, `name`) VALUES (NULL, '企業');

INSERT INTO `school_tbl`(`school_id`, `name`, `abbreviation`, `code`) VALUES (null,'麻生情報ビジネス専門学校','ABCC','1');
INSERT INTO `school_tbl`(`school_id`, `name`, `abbreviation`, `code`) VALUES (null,'麻生外語観光＆ブライダル専門学校','AFTC','2');
INSERT INTO `school_tbl`(`school_id`, `name`, `abbreviation`, `code`) VALUES (null,'麻生医療福祉専門学校福岡校','AMFC','7');
INSERT INTO `school_tbl`(`school_id`, `name`, `abbreviation`, `code`) VALUES (null,'麻生建築＆デザイン専門学校','AADC','8');
INSERT INTO `school_tbl`(`school_id`, `name`, `abbreviation`, `code`) VALUES (null,'麻生美容専門学校','ABC','11');
INSERT INTO `school_tbl`(`school_id`, `name`, `abbreviation`, `code`) VALUES (null,'麻生公務員専門学校福岡校','APFC','12');
INSERT INTO `school_tbl`(`school_id`, `name`, `abbreviation`, `code`) VALUES (null,'ＡＳＯポップカルチャー専門学校','APC','16');
INSERT INTO `school_tbl`(`school_id`, `name`, `abbreviation`, `code`) VALUES (null,'ＡＳＯ高等部','APS','17');

INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'情報ビジネス科',(SELECT school_id FROM school_tbl where name='麻生情報ビジネス専門学校'),'54');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'経営ビジネス科',(SELECT school_id FROM school_tbl where name='麻生情報ビジネス専門学校'),'129');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'経理科',(SELECT school_id FROM school_tbl where name='麻生情報ビジネス専門学校'),'130');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'国際ビジネス科',(SELECT school_id FROM school_tbl where name='麻生情報ビジネス専門学校'),'133');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'ビジネスエキスパート科',(SELECT school_id FROM school_tbl where name='麻生情報ビジネス専門学校'),'135');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'情報工学科 高度ＩＴシステム専攻',(SELECT school_id FROM school_tbl where name='麻生情報ビジネス専門学校'),'139');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'情報工学科 高度ネットワーク・セキュリティ専攻',(SELECT school_id FROM school_tbl where name='麻生情報ビジネス専門学校'),'140');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'情報工学科 電子システム工学専攻',(SELECT school_id FROM school_tbl where name='麻生情報ビジネス専門学校'),'141');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'情報システム専攻科 システムエンジニア専攻アドバンスコース',(SELECT school_id FROM school_tbl where name='麻生情報ビジネス専門学校'),'142');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'情報システム専攻科 システムエンジニア専攻',(SELECT school_id FROM school_tbl where name='麻生情報ビジネス専門学校'),'143');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'情報システム専攻科 ネットワークエンジニア専攻',(SELECT school_id FROM school_tbl where name='麻生情報ビジネス専門学校'),'144');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'情報システム科 プログラミング専攻アドバンスコース',(SELECT school_id FROM school_tbl where name='麻生情報ビジネス専門学校'),'146');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'情報システム科 プログラミング専攻',(SELECT school_id FROM school_tbl where name='麻生情報ビジネス専門学校'),'147');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'情報システム科 ネットワーク専攻',(SELECT school_id FROM school_tbl where name='麻生情報ビジネス専門学校'),'148');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'国際ＩＴエンジニア科',(SELECT school_id FROM school_tbl where name='麻生情報ビジネス専門学校'),'150');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'情報システム専攻科 ネットワークエンジニア専攻アドバンスコース',(SELECT school_id FROM school_tbl where name='麻生情報ビジネス専門学校'),'153');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'情報システム科 ネットワーク専攻アドバンスコース',(SELECT school_id FROM school_tbl where name='麻生情報ビジネス専門学校'),'154');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'情報工学科　ＡＩ＆ＩｏＴ専攻',(SELECT school_id FROM school_tbl where name='麻生情報ビジネス専門学校'),'155');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'情報システム専攻科　ＡＩエンジニア専攻',(SELECT school_id FROM school_tbl where name='麻生情報ビジネス専門学校'),'156');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'情報システム科　ＡＩプログラミング専攻',(SELECT school_id FROM school_tbl where name='麻生情報ビジネス専門学校'),'157');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'情報システム専攻科　ＡＩエンジニア専攻アドバンスコース',(SELECT school_id FROM school_tbl where name='麻生情報ビジネス専門学校'),'158');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'情報システム科　ＡＩプログラミング専攻アドバンスコース',(SELECT school_id FROM school_tbl where name='麻生情報ビジネス専門学校'),'159');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'国際ＩＴエンジニア科',(SELECT school_id FROM school_tbl where name='麻生情報ビジネス専門学校'),'160');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'日本語科（１年）',(SELECT school_id FROM school_tbl where name='麻生外語観光＆ブライダル専門学校'),'6');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'エアライン科',(SELECT school_id FROM school_tbl where name='麻生外語観光＆ブライダル専門学校'),'32');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'日本語科（１年６か月）',(SELECT school_id FROM school_tbl where name='麻生外語観光＆ブライダル専門学校'),'39');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'海外ビジネス科',(SELECT school_id FROM school_tbl where name='麻生外語観光＆ブライダル専門学校'),'43');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'エアポート科',(SELECT school_id FROM school_tbl where name='麻生外語観光＆ブライダル専門学校'),'44');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'英語コミュニケーション科',(SELECT school_id FROM school_tbl where name='麻生外語観光＆ブライダル専門学校'),'47');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'ブライダル・ウエディング科',(SELECT school_id FROM school_tbl where name='麻生外語観光＆ブライダル専門学校'),'51');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'トラベル科',(SELECT school_id FROM school_tbl where name='麻生外語観光＆ブライダル専門学校'),'52');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'日本語科（２年）',(SELECT school_id FROM school_tbl where name='麻生外語観光＆ブライダル専門学校'),'53');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'ホテル・リゾート科 ホテル・リゾートコース',(SELECT school_id FROM school_tbl where name='麻生外語観光＆ブライダル専門学校'),'56');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'ホテル・リゾート科 海外インターンシップコース',(SELECT school_id FROM school_tbl where name='麻生外語観光＆ブライダル専門学校'),'57');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'エアライン科　キャビンアテンダントコース',(SELECT school_id FROM school_tbl where name='麻生外語観光＆ブライダル専門学校'),'59');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'エアライン科　グランドスタッフコース',(SELECT school_id FROM school_tbl where name='麻生外語観光＆ブライダル専門学校'),'60');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'エアライン科　グランドハンドリングコース',(SELECT school_id FROM school_tbl where name='麻生外語観光＆ブライダル専門学校'),'61');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'エアポート科',(SELECT school_id FROM school_tbl where name='麻生外語観光＆ブライダル専門学校'),'62');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'国際おもてなし科',(SELECT school_id FROM school_tbl where name='麻生外語観光＆ブライダル専門学校'),'68');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'グローバルコミュニケーション科　英語コミュニケーションコース',(SELECT school_id FROM school_tbl where name='麻生外語観光＆ブライダル専門学校'),'69');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'グローバルコミュニケーション科　韓国語コミュニケーションコース',(SELECT school_id FROM school_tbl where name='麻生外語観光＆ブライダル専門学校'),'70');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'グローバルコミュニケーション科　グローバルビジネスコース',(SELECT school_id FROM school_tbl where name='麻生外語観光＆ブライダル専門学校'),'71');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'グローバルコミュニケーション科　国際ツーリズムコース',(SELECT school_id FROM school_tbl where name='麻生外語観光＆ブライダル専門学校'),'72');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'介護福祉科',(SELECT school_id FROM school_tbl where name='麻生医療福祉専門学校福岡校'),'1');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'社会福祉科',(SELECT school_id FROM school_tbl where name='麻生医療福祉専門学校福岡校'),'11');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'ソーシャルワーカー科',(SELECT school_id FROM school_tbl where name='麻生医療福祉専門学校福岡校'),'12');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'診療情報管理士科',(SELECT school_id FROM school_tbl where name='麻生医療福祉専門学校福岡校'),'17');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'こども未来学科',(SELECT school_id FROM school_tbl where name='麻生医療福祉専門学校福岡校'),'22');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'社会福祉士養成通信課程',(SELECT school_id FROM school_tbl where name='麻生医療福祉専門学校福岡校'),'24');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'福祉心理学科',(SELECT school_id FROM school_tbl where name='麻生医療福祉専門学校福岡校'),'30');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'診療情報管理士専攻科',(SELECT school_id FROM school_tbl where name='麻生医療福祉専門学校福岡校'),'31');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'医療秘書・事務科',(SELECT school_id FROM school_tbl where name='麻生医療福祉専門学校福岡校'),'32');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'国際介護福祉科',(SELECT school_id FROM school_tbl where name='麻生医療福祉専門学校福岡校'),'33');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'こども保育科',(SELECT school_id FROM school_tbl where name='麻生医療福祉専門学校福岡校'),'34');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'建築ＣＡＤ科',(SELECT school_id FROM school_tbl where name='麻生建築＆デザイン専門学校'),'7');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'建築学科（夜間）',(SELECT school_id FROM school_tbl where name='麻生建築＆デザイン専門学校'),'13');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'建築工学科',(SELECT school_id FROM school_tbl where name='麻生建築＆デザイン専門学校'),'20');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'建築学科',(SELECT school_id FROM school_tbl where name='麻生建築＆デザイン専門学校'),'21');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'インテリアデザイン科',(SELECT school_id FROM school_tbl where name='麻生建築＆デザイン専門学校'),'22');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'建築士専攻科',(SELECT school_id FROM school_tbl where name='麻生建築＆デザイン専門学校'),'24');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'クリエイティブデザイン学科プロダクトデザイン専攻',(SELECT school_id FROM school_tbl where name='麻生建築＆デザイン専門学校'),'26');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'クリエイティブデザイン学科ビジュアルデザイン専攻',(SELECT school_id FROM school_tbl where name='麻生建築＆デザイン専門学校'),'27');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'美容科（昼間課程）',(SELECT school_id FROM school_tbl where name='麻生美容専門学校'),'1');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'美容科通信教育課程',(SELECT school_id FROM school_tbl where name='麻生美容専門学校'),'4');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'公務員専攻科',(SELECT school_id FROM school_tbl where name='麻生公務員専門学校福岡校'),'1');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'公務員総合科',(SELECT school_id FROM school_tbl where name='麻生公務員専門学校福岡校'),'2');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'公務員中上級専攻科',(SELECT school_id FROM school_tbl where name='麻生公務員専門学校福岡校'),'3');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'公務員中上級教養科',(SELECT school_id FROM school_tbl where name='麻生公務員専門学校福岡校'),'5');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'ゲーム・ＣＧ・アニメ専攻科 ゲーム専攻',(SELECT school_id FROM school_tbl where name='ＡＳＯポップカルチャー専門学校'),'1');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'ゲーム・ＣＧ・アニメ専攻科 ＣＧ専攻',(SELECT school_id FROM school_tbl where name='ＡＳＯポップカルチャー専門学校'),'2');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'ゲーム・ＣＧ・アニメ科 ゲームコース',(SELECT school_id FROM school_tbl where name='ＡＳＯポップカルチャー専門学校'),'4');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'ゲーム・ＣＧ・アニメ科 ＣＧコース',(SELECT school_id FROM school_tbl where name='ＡＳＯポップカルチャー専門学校'),'5');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'ゲーム・ＣＧ・アニメ科 アニメコース',(SELECT school_id FROM school_tbl where name='ＡＳＯポップカルチャー専門学校'),'6');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'ゲーム・ＣＧ専攻科 ゲーム専攻',(SELECT school_id FROM school_tbl where name='ＡＳＯポップカルチャー専門学校'),'15');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'ゲーム・ＣＧ専攻科 ＣＧ専攻',(SELECT school_id FROM school_tbl where name='ＡＳＯポップカルチャー専門学校'),'16');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'マンガ・イラスト科 マンガコース',(SELECT school_id FROM school_tbl where name='ＡＳＯポップカルチャー専門学校'),'17');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'マンガ・イラスト科 イラストコース',(SELECT school_id FROM school_tbl where name='ＡＳＯポップカルチャー専門学校'),'18');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'ゲーム専攻科',(SELECT school_id FROM school_tbl where name='ＡＳＯポップカルチャー専門学校'),'20');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'ゲーム学科',(SELECT school_id FROM school_tbl where name='ＡＳＯポップカルチャー専門学校'),'21');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'ＣＧ専攻科',(SELECT school_id FROM school_tbl where name='ＡＳＯポップカルチャー専門学校'),'22');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'ＣＧ学科',(SELECT school_id FROM school_tbl where name='ＡＳＯポップカルチャー専門学校'),'23');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'アニメ学科',(SELECT school_id FROM school_tbl where name='ＡＳＯポップカルチャー専門学校'),'24');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'コミックイラスト科　アニメコース',(SELECT school_id FROM school_tbl where name='ＡＳＯポップカルチャー専門学校'),'25');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'マンガ学科',(SELECT school_id FROM school_tbl where name='ＡＳＯポップカルチャー専門学校'),'26');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'コミックイラスト科　マンガコース',(SELECT school_id FROM school_tbl where name='ＡＳＯポップカルチャー専門学校'),'27');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'イラスト学科',(SELECT school_id FROM school_tbl where name='ＡＳＯポップカルチャー専門学校'),'28');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'コミックイラスト科　イラストコース',(SELECT school_id FROM school_tbl where name='ＡＳＯポップカルチャー専門学校'),'29');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'コミックイラスト研究科',(SELECT school_id FROM school_tbl where name='ＡＳＯポップカルチャー専門学校'),'30');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'情報システムコース',(SELECT school_id FROM school_tbl where name='ＡＳＯ高等部'),'1');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'ゲームクリエイターコース',(SELECT school_id FROM school_tbl where name='ＡＳＯ高等部'),'2');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'CG・イラストコース',(SELECT school_id FROM school_tbl where name='ＡＳＯ高等部'),'3');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'システムナレッジコース',(SELECT school_id FROM school_tbl where name='ＡＳＯ高等部'),'4');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'ゲームナレッジコース',(SELECT school_id FROM school_tbl where name='ＡＳＯ高等部'),'5');
INSERT INTO `department_tbl`(`department_id`, `name`, `school_id`, `code`) VALUES (null,'イラストナレッジコース',(SELECT school_id FROM school_tbl where name='ＡＳＯ高等部'),'6');

INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'A',(SELECT department_id FROM department_tbl where name='情報ビジネス科'),(SELECT admin_id FROM admin_tbl where name='佐々木　美恵'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'B',(SELECT department_id FROM department_tbl where name='情報ビジネス科'),(SELECT admin_id FROM admin_tbl where name='藤本　清貴'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='情報ビジネス科'),(SELECT admin_id FROM admin_tbl where name='下假屋　珠美'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='経営ビジネス科'),(SELECT admin_id FROM admin_tbl where name='藤本　清貴'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='経営ビジネス科'),(SELECT admin_id FROM admin_tbl where name='姫嶋　幸子'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='経理科'),(SELECT admin_id FROM admin_tbl where name='山田　奈々瀬'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='経理科'),(SELECT admin_id FROM admin_tbl where name='新田　覚'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='国際ビジネス科'),(SELECT admin_id FROM admin_tbl where name='寺﨑　葉子'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'A',(SELECT department_id FROM department_tbl where name='国際ビジネス科'),(SELECT admin_id FROM admin_tbl where name='田中　雅彦'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'B',(SELECT department_id FROM department_tbl where name='国際ビジネス科'),(SELECT admin_id FROM admin_tbl where name='福永　沙耶花'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='ビジネスエキスパート科'),(SELECT admin_id FROM admin_tbl where name='田中　陽子'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='ビジネスエキスパート科'),(SELECT admin_id FROM admin_tbl where name='瀬崎　美佐緒'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'IT1A',(SELECT department_id FROM department_tbl where name='情報工学科 高度ＩＴシステム専攻'),(SELECT admin_id FROM admin_tbl where name='志水　徹'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'IT1B',(SELECT department_id FROM department_tbl where name='情報工学科 高度ＩＴシステム専攻'),(SELECT admin_id FROM admin_tbl where name='西宮　颯'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'SD2A',(SELECT department_id FROM department_tbl where name='情報工学科 高度ＩＴシステム専攻'),(SELECT admin_id FROM admin_tbl where name='西野　直幸'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'SD3A',(SELECT department_id FROM department_tbl where name='情報工学科 高度ＩＴシステム専攻'),(SELECT admin_id FROM admin_tbl where name='藤澤　昌聡'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'SD4',(SELECT department_id FROM department_tbl where name='情報工学科 高度ＩＴシステム専攻'),(SELECT admin_id FROM admin_tbl where name='手嶋　隆之'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'IT1B',(SELECT department_id FROM department_tbl where name='情報工学科 高度ネットワーク・セキュリティ専攻'),(SELECT admin_id FROM admin_tbl where name='西宮　颯'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'NS2A',(SELECT department_id FROM department_tbl where name='情報工学科 高度ネットワーク・セキュリティ専攻'),(SELECT admin_id FROM admin_tbl where name='北島　仁宇'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'NS3B',(SELECT department_id FROM department_tbl where name='情報工学科 高度ネットワーク・セキュリティ専攻'),(SELECT admin_id FROM admin_tbl where name='久保山　大地'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'NS4',(SELECT department_id FROM department_tbl where name='情報工学科 高度ネットワーク・セキュリティ専攻'),(SELECT admin_id FROM admin_tbl where name='久保山　大地'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'ES4',(SELECT department_id FROM department_tbl where name='情報工学科 電子システム工学専攻'),(SELECT admin_id FROM admin_tbl where name='久家　政人'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'SD2A',(SELECT department_id FROM department_tbl where name='情報システム専攻科 システムエンジニア専攻アドバンスコース'),(SELECT admin_id FROM admin_tbl where name='西野　直幸'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'SD3A',(SELECT department_id FROM department_tbl where name='情報システム専攻科 システムエンジニア専攻アドバンスコース'),(SELECT admin_id FROM admin_tbl where name='藤澤　昌聡'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'SD4',(SELECT department_id FROM department_tbl where name='情報システム専攻科 システムエンジニア専攻アドバンスコース'),(SELECT admin_id FROM admin_tbl where name='手嶋　隆之'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'IT1C',(SELECT department_id FROM department_tbl where name='情報システム専攻科 システムエンジニア専攻'),(SELECT admin_id FROM admin_tbl where name='今村　美穂'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'IT1D',(SELECT department_id FROM department_tbl where name='情報システム専攻科 システムエンジニア専攻'),(SELECT admin_id FROM admin_tbl where name='毛利　俊司'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'IT1E',(SELECT department_id FROM department_tbl where name='情報システム専攻科 システムエンジニア専攻'),(SELECT admin_id FROM admin_tbl where name='奥野　広成'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'IT1F',(SELECT department_id FROM department_tbl where name='情報システム専攻科 システムエンジニア専攻'),(SELECT admin_id FROM admin_tbl where name='小井手　武治'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'SD2B',(SELECT department_id FROM department_tbl where name='情報システム専攻科 システムエンジニア専攻'),(SELECT admin_id FROM admin_tbl where name='村上　香代'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'SD2C',(SELECT department_id FROM department_tbl where name='情報システム専攻科 システムエンジニア専攻'),(SELECT admin_id FROM admin_tbl where name='川野　啓祐'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'SD2D',(SELECT department_id FROM department_tbl where name='情報システム専攻科 システムエンジニア専攻'),(SELECT admin_id FROM admin_tbl where name='前園　勝稔'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'SD2E',(SELECT department_id FROM department_tbl where name='情報システム専攻科 システムエンジニア専攻'),(SELECT admin_id FROM admin_tbl where name='野馬 克則'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'SD3B',(SELECT department_id FROM department_tbl where name='情報システム専攻科 システムエンジニア専攻'),(SELECT admin_id FROM admin_tbl where name='久家　政人'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'SD3C',(SELECT department_id FROM department_tbl where name='情報システム専攻科 システムエンジニア専攻'),(SELECT admin_id FROM admin_tbl where name='香川　文紀'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'SD3D',(SELECT department_id FROM department_tbl where name='情報システム専攻科 システムエンジニア専攻'),(SELECT admin_id FROM admin_tbl where name='正路　文德'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'SD3E',(SELECT department_id FROM department_tbl where name='情報システム専攻科 システムエンジニア専攻'),(SELECT admin_id FROM admin_tbl where name='高橋　政博'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'IT1C',(SELECT department_id FROM department_tbl where name='情報システム専攻科 ネットワークエンジニア専攻'),(SELECT admin_id FROM admin_tbl where name='今村　美穂'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'IT1F',(SELECT department_id FROM department_tbl where name='情報システム専攻科 ネットワークエンジニア専攻'),(SELECT admin_id FROM admin_tbl where name='小井手　武治'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'NS2A',(SELECT department_id FROM department_tbl where name='情報システム専攻科 ネットワークエンジニア専攻'),(SELECT admin_id FROM admin_tbl where name='北島　仁宇'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'NS3A',(SELECT department_id FROM department_tbl where name='情報システム専攻科 ネットワークエンジニア専攻'),(SELECT admin_id FROM admin_tbl where name='高倉　美哉'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'SD2B',(SELECT department_id FROM department_tbl where name='情報システム科 プログラミング専攻アドバンスコース'),(SELECT admin_id FROM admin_tbl where name='村上　香代'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'IT1G',(SELECT department_id FROM department_tbl where name='情報システム科 プログラミング専攻'),(SELECT admin_id FROM admin_tbl where name='江利　かおり'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'IT1H',(SELECT department_id FROM department_tbl where name='情報システム科 プログラミング専攻'),(SELECT admin_id FROM admin_tbl where name='川原　弓佳'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'SD2F',(SELECT department_id FROM department_tbl where name='情報システム科 プログラミング専攻'),(SELECT admin_id FROM admin_tbl where name='小渕　洋子'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'SD2G',(SELECT department_id FROM department_tbl where name='情報システム科 プログラミング専攻'),(SELECT admin_id FROM admin_tbl where name='染矢　裕美子'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'IT1H',(SELECT department_id FROM department_tbl where name='情報システム科 ネットワーク専攻'),(SELECT admin_id FROM admin_tbl where name='川原　弓佳'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'NS2B',(SELECT department_id FROM department_tbl where name='情報システム科 ネットワーク専攻'),(SELECT admin_id FROM admin_tbl where name='打越　直美'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='国際ＩＴエンジニア科'),(SELECT admin_id FROM admin_tbl where name='底田　浩次'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'NS4',(SELECT department_id FROM department_tbl where name='情報システム専攻科 ネットワークエンジニア専攻アドバンスコース'),(SELECT admin_id FROM admin_tbl where name='久保山　大地'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'NS2A',(SELECT department_id FROM department_tbl where name='情報システム科 ネットワーク専攻アドバンスコース'),(SELECT admin_id FROM admin_tbl where name='北島　仁宇'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'IT1A',(SELECT department_id FROM department_tbl where name='情報工学科　ＡＩ＆ＩｏＴ専攻'),(SELECT admin_id FROM admin_tbl where name='志水　徹'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'AI2',(SELECT department_id FROM department_tbl where name='情報工学科　ＡＩ＆ＩｏＴ専攻'),(SELECT admin_id FROM admin_tbl where name='山下　文夫'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'AI3',(SELECT department_id FROM department_tbl where name='情報工学科　ＡＩ＆ＩｏＴ専攻'),(SELECT admin_id FROM admin_tbl where name='元田　真史'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'IT1A',(SELECT department_id FROM department_tbl where name='情報システム専攻科　ＡＩエンジニア専攻'),(SELECT admin_id FROM admin_tbl where name='志水　徹'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'IT1C',(SELECT department_id FROM department_tbl where name='情報システム専攻科　ＡＩエンジニア専攻'),(SELECT admin_id FROM admin_tbl where name='今村　美穂'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'AI2',(SELECT department_id FROM department_tbl where name='情報システム専攻科　ＡＩエンジニア専攻'),(SELECT admin_id FROM admin_tbl where name='山下　文夫'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'AI3',(SELECT department_id FROM department_tbl where name='情報システム専攻科　ＡＩエンジニア専攻'),(SELECT admin_id FROM admin_tbl where name='元田　真史'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'IT1G',(SELECT department_id FROM department_tbl where name='情報システム科　ＡＩプログラミング専攻'),(SELECT admin_id FROM admin_tbl where name='江利　かおり'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'AI2',(SELECT department_id FROM department_tbl where name='情報システム科　ＡＩプログラミング専攻'),(SELECT admin_id FROM admin_tbl where name='山下　文夫'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'AI2',(SELECT department_id FROM department_tbl where name='情報システム専攻科　ＡＩエンジニア専攻アドバンスコース'),(SELECT admin_id FROM admin_tbl where name='山下　文夫'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'AI3',(SELECT department_id FROM department_tbl where name='情報システム専攻科　ＡＩエンジニア専攻アドバンスコース'),(SELECT admin_id FROM admin_tbl where name='元田　真史'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'AI2',(SELECT department_id FROM department_tbl where name='情報システム科　ＡＩプログラミング専攻アドバンスコース'),(SELECT admin_id FROM admin_tbl where name='山下　文夫'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'AI3',(SELECT department_id FROM department_tbl where name='情報システム科　ＡＩプログラミング専攻アドバンスコース'),(SELECT admin_id FROM admin_tbl where name='元田　真史'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='国際ＩＴエンジニア科'),(SELECT admin_id FROM admin_tbl where name='寺﨑　葉子'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'G',(SELECT department_id FROM department_tbl where name='日本語科（１年）'),(SELECT admin_id FROM admin_tbl where name='村上　陽子'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'H',(SELECT department_id FROM department_tbl where name='日本語科（１年）'),(SELECT admin_id FROM admin_tbl where name='村上　陽子'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='エアライン科'),(SELECT admin_id FROM admin_tbl where name='宮﨑　みゆき'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'1A',(SELECT department_id FROM department_tbl where name='日本語科（１年６か月）'),(SELECT admin_id FROM admin_tbl where name='日浦　由布子'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'1B',(SELECT department_id FROM department_tbl where name='日本語科（１年６か月）'),(SELECT admin_id FROM admin_tbl where name='日浦　由布子'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'1C',(SELECT department_id FROM department_tbl where name='日本語科（１年６か月）'),(SELECT admin_id FROM admin_tbl where name='藤井　成樹'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'1D',(SELECT department_id FROM department_tbl where name='日本語科（１年６か月）'),(SELECT admin_id FROM admin_tbl where name='藤井　成樹'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'1E',(SELECT department_id FROM department_tbl where name='日本語科（１年６か月）'),(SELECT admin_id FROM admin_tbl where name='椎木　睦'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'B',(SELECT department_id FROM department_tbl where name='日本語科（１年６か月）'),(SELECT admin_id FROM admin_tbl where name='河原田　純子'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'C',(SELECT department_id FROM department_tbl where name='日本語科（１年６か月）'),(SELECT admin_id FROM admin_tbl where name='河原田　純子'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'D',(SELECT department_id FROM department_tbl where name='日本語科（１年６か月）'),(SELECT admin_id FROM admin_tbl where name='河崎　新弥'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'E',(SELECT department_id FROM department_tbl where name='日本語科（１年６か月）'),(SELECT admin_id FROM admin_tbl where name='河崎　新弥'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'F',(SELECT department_id FROM department_tbl where name='日本語科（１年６か月）'),(SELECT admin_id FROM admin_tbl where name='楢崎　幸彦'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='海外ビジネス科'),(SELECT admin_id FROM admin_tbl where name='秋本　佐代子'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='エアポート科'),(SELECT admin_id FROM admin_tbl where name='三苫　秀一郎'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='英語コミュニケーション科'),(SELECT admin_id FROM admin_tbl where name='中山　久豪'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'A',(SELECT department_id FROM department_tbl where name='ブライダル・ウエディング科'),(SELECT admin_id FROM admin_tbl where name='中村　直輝'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'B',(SELECT department_id FROM department_tbl where name='ブライダル・ウエディング科'),(SELECT admin_id FROM admin_tbl where name='瀧口　恵子'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='ブライダル・ウエディング科'),(SELECT admin_id FROM admin_tbl where name='東　まゆみ'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='トラベル科'),(SELECT admin_id FROM admin_tbl where name='和田　菜穂'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'I',(SELECT department_id FROM department_tbl where name='日本語科（２年）'),(SELECT admin_id FROM admin_tbl where name='柴藤　絵美'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'J',(SELECT department_id FROM department_tbl where name='日本語科（２年）'),(SELECT admin_id FROM admin_tbl where name='柴藤　絵美'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'A',(SELECT department_id FROM department_tbl where name='日本語科（２年）'),(SELECT admin_id FROM admin_tbl where name='楢崎　幸彦'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'A',(SELECT department_id FROM department_tbl where name='ホテル・リゾート科 ホテル・リゾートコース'),(SELECT admin_id FROM admin_tbl where name='一岡　浩己'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'B',(SELECT department_id FROM department_tbl where name='ホテル・リゾート科 ホテル・リゾートコース'),(SELECT admin_id FROM admin_tbl where name='小形　享平'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='ホテル・リゾート科 ホテル・リゾートコース'),(SELECT admin_id FROM admin_tbl where name='木村　匡志'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'B',(SELECT department_id FROM department_tbl where name='ホテル・リゾート科 海外インターンシップコース'),(SELECT admin_id FROM admin_tbl where name='小形　享平'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'A',(SELECT department_id FROM department_tbl where name='エアライン科　キャビンアテンダントコース'),(SELECT admin_id FROM admin_tbl where name='平田　かおり'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'B',(SELECT department_id FROM department_tbl where name='エアライン科　キャビンアテンダントコース'),(SELECT admin_id FROM admin_tbl where name='大久保　舞'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'A',(SELECT department_id FROM department_tbl where name='エアライン科　グランドスタッフコース'),(SELECT admin_id FROM admin_tbl where name='平田　かおり'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'B',(SELECT department_id FROM department_tbl where name='エアライン科　グランドスタッフコース'),(SELECT admin_id FROM admin_tbl where name='大久保　舞'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'A',(SELECT department_id FROM department_tbl where name='エアライン科　グランドハンドリングコース'),(SELECT admin_id FROM admin_tbl where name='平田　かおり'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='エアポート科'),(SELECT admin_id FROM admin_tbl where name='三苫　秀一郎'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='グローバルコミュニケーション科　英語コミュニケーションコース'),(SELECT admin_id FROM admin_tbl where name='野々村　賢一'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='グローバルコミュニケーション科　韓国語コミュニケーションコース'),(SELECT admin_id FROM admin_tbl where name='岡本　彩'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='グローバルコミュニケーション科　グローバルビジネスコース'),(SELECT admin_id FROM admin_tbl where name='若松　昌枝'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='グローバルコミュニケーション科　国際ツーリズムコース'),(SELECT admin_id FROM admin_tbl where name='若松　昌枝'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='介護福祉科'),(SELECT admin_id FROM admin_tbl where name='吉水　美穂'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='介護福祉科'),(SELECT admin_id FROM admin_tbl where name='平山　恵子'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='社会福祉科'),(SELECT admin_id FROM admin_tbl where name='下川　武志'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='社会福祉科'),(SELECT admin_id FROM admin_tbl where name='西村　明洋'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='社会福祉科'),(SELECT admin_id FROM admin_tbl where name='川原　ゆり'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='ソーシャルワーカー科'),(SELECT admin_id FROM admin_tbl where name='亀田　尚'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='診療情報管理士科'),(SELECT admin_id FROM admin_tbl where name='前田　浩明'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='診療情報管理士科'),(SELECT admin_id FROM admin_tbl where name='髙田　ゆかり'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='診療情報管理士科'),(SELECT admin_id FROM admin_tbl where name='髙田　ゆかり'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='こども未来学科'),(SELECT admin_id FROM admin_tbl where name='若狭　恵美'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='こども未来学科'),(SELECT admin_id FROM admin_tbl where name='若狭　恵美'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='こども未来学科'),(SELECT admin_id FROM admin_tbl where name='鎌田　昇子'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='福祉心理学科'),(SELECT admin_id FROM admin_tbl where name='馬場　一美'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='福祉心理学科'),(SELECT admin_id FROM admin_tbl where name='中山　かおり'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='福祉心理学科'),(SELECT admin_id FROM admin_tbl where name='森田　康雅'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='診療情報管理士専攻科'),(SELECT admin_id FROM admin_tbl where name='髙田　ゆかり'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='医療秘書・事務科'),(SELECT admin_id FROM admin_tbl where name='土屋　亜生子'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='医療秘書・事務科'),(SELECT admin_id FROM admin_tbl where name='勝見　令子'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='こども保育科'),(SELECT admin_id FROM admin_tbl where name='稲永　奈歩'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='こども保育科'),(SELECT admin_id FROM admin_tbl where name='上村　仁美'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'A',(SELECT department_id FROM department_tbl where name='建築ＣＡＤ科'),(SELECT admin_id FROM admin_tbl where name='古田　洋仁'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'B',(SELECT department_id FROM department_tbl where name='建築ＣＡＤ科'),(SELECT admin_id FROM admin_tbl where name='笠　真由美'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'A',(SELECT department_id FROM department_tbl where name='建築ＣＡＤ科'),(SELECT admin_id FROM admin_tbl where name='吉田　麻美'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'B',(SELECT department_id FROM department_tbl where name='建築ＣＡＤ科'),(SELECT admin_id FROM admin_tbl where name='永田　将大'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='建築学科（夜間）'),(SELECT admin_id FROM admin_tbl where name='田川　裕也'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='建築学科（夜間）'),(SELECT admin_id FROM admin_tbl where name='田川　裕也'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'A',(SELECT department_id FROM department_tbl where name='建築工学科'),(SELECT admin_id FROM admin_tbl where name='清水　道敏'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'B',(SELECT department_id FROM department_tbl where name='建築工学科'),(SELECT admin_id FROM admin_tbl where name='松川　渚'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'C',(SELECT department_id FROM department_tbl where name='建築工学科'),(SELECT admin_id FROM admin_tbl where name='福光　春子'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'A',(SELECT department_id FROM department_tbl where name='建築工学科'),(SELECT admin_id FROM admin_tbl where name='佐藤　桃子'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'B',(SELECT department_id FROM department_tbl where name='建築工学科'),(SELECT admin_id FROM admin_tbl where name='西尾　英士'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'C',(SELECT department_id FROM department_tbl where name='建築工学科'),(SELECT admin_id FROM admin_tbl where name='石本　洋士'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'A',(SELECT department_id FROM department_tbl where name='建築工学科'),(SELECT admin_id FROM admin_tbl where name='八尋　誠'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'B',(SELECT department_id FROM department_tbl where name='建築工学科'),(SELECT admin_id FROM admin_tbl where name='宗吉　隼一'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'C',(SELECT department_id FROM department_tbl where name='建築工学科'),(SELECT admin_id FROM admin_tbl where name='古賀　俊光'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'A',(SELECT department_id FROM department_tbl where name='建築学科'),(SELECT admin_id FROM admin_tbl where name='峯元　幹雄'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'B',(SELECT department_id FROM department_tbl where name='建築学科'),(SELECT admin_id FROM admin_tbl where name='徳田　美穂子'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'A',(SELECT department_id FROM department_tbl where name='建築学科'),(SELECT admin_id FROM admin_tbl where name='集路　正己'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'B',(SELECT department_id FROM department_tbl where name='建築学科'),(SELECT admin_id FROM admin_tbl where name='中園　理恵子'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'A',(SELECT department_id FROM department_tbl where name='インテリアデザイン科'),(SELECT admin_id FROM admin_tbl where name='山本　佳明'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'B',(SELECT department_id FROM department_tbl where name='インテリアデザイン科'),(SELECT admin_id FROM admin_tbl where name='赤星　亜美'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='インテリアデザイン科'),(SELECT admin_id FROM admin_tbl where name='工藤　有紀'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='建築士専攻科'),(SELECT admin_id FROM admin_tbl where name='森行　美枝'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='クリエイティブデザイン学科プロダクトデザイン専攻'),(SELECT admin_id FROM admin_tbl where name='稲吉　貴博'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='クリエイティブデザイン学科プロダクトデザイン専攻'),(SELECT admin_id FROM admin_tbl where name='稲吉　貴博'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='クリエイティブデザイン学科ビジュアルデザイン専攻'),(SELECT admin_id FROM admin_tbl where name='飯田　康介'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='クリエイティブデザイン学科ビジュアルデザイン専攻'),(SELECT admin_id FROM admin_tbl where name='松本　剛太'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'A',(SELECT department_id FROM department_tbl where name='美容科（昼間課程）'),(SELECT admin_id FROM admin_tbl where name='西依　優'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'B',(SELECT department_id FROM department_tbl where name='美容科（昼間課程）'),(SELECT admin_id FROM admin_tbl where name='荒木　成美'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'C',(SELECT department_id FROM department_tbl where name='美容科（昼間課程）'),(SELECT admin_id FROM admin_tbl where name='石井　祐輔'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'A',(SELECT department_id FROM department_tbl where name='美容科（昼間課程）'),(SELECT admin_id FROM admin_tbl where name='江藤　登志美'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'B',(SELECT department_id FROM department_tbl where name='美容科（昼間課程）'),(SELECT admin_id FROM admin_tbl where name='森　建太'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'A',(SELECT department_id FROM department_tbl where name='公務員専攻科'),(SELECT admin_id FROM admin_tbl where name='松隈　達也'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'B',(SELECT department_id FROM department_tbl where name='公務員専攻科'),(SELECT admin_id FROM admin_tbl where name='桑原　賢'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'C',(SELECT department_id FROM department_tbl where name='公務員専攻科'),(SELECT admin_id FROM admin_tbl where name='梶村　勝治'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'D',(SELECT department_id FROM department_tbl where name='公務員専攻科'),(SELECT admin_id FROM admin_tbl where name='鬼塚　勇'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'A',(SELECT department_id FROM department_tbl where name='公務員総合科'),(SELECT admin_id FROM admin_tbl where name='横山　真太郎'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'B',(SELECT department_id FROM department_tbl where name='公務員総合科'),(SELECT admin_id FROM admin_tbl where name='甲斐　友康'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'C',(SELECT department_id FROM department_tbl where name='公務員総合科'),(SELECT admin_id FROM admin_tbl where name='江藤　弘明'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'D',(SELECT department_id FROM department_tbl where name='公務員総合科'),(SELECT admin_id FROM admin_tbl where name='船木　竜太'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'E',(SELECT department_id FROM department_tbl where name='公務員総合科'),(SELECT admin_id FROM admin_tbl where name='豊田　亮'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'F',(SELECT department_id FROM department_tbl where name='公務員総合科'),(SELECT admin_id FROM admin_tbl where name='小島　俊宣'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'A',(SELECT department_id FROM department_tbl where name='公務員総合科'),(SELECT admin_id FROM admin_tbl where name='福田　一総'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'B',(SELECT department_id FROM department_tbl where name='公務員総合科'),(SELECT admin_id FROM admin_tbl where name='本多　利幸'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'C',(SELECT department_id FROM department_tbl where name='公務員総合科'),(SELECT admin_id FROM admin_tbl where name='山端　亜弥'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'D',(SELECT department_id FROM department_tbl where name='公務員総合科'),(SELECT admin_id FROM admin_tbl where name='田中　純一'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'E',(SELECT department_id FROM department_tbl where name='公務員総合科'),(SELECT admin_id FROM admin_tbl where name='長友　裕幸'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'F',(SELECT department_id FROM department_tbl where name='公務員総合科'),(SELECT admin_id FROM admin_tbl where name='賀来　美和'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='公務員中上級専攻科'),(SELECT admin_id FROM admin_tbl where name='名越　大介'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='公務員中上級教養科'),(SELECT admin_id FROM admin_tbl where name='花水　倫尚'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='ゲーム・ＣＧ・アニメ専攻科 ゲーム専攻'),(SELECT admin_id FROM admin_tbl where name='柴岡　秀信'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='ゲーム・ＣＧ・アニメ専攻科 ゲーム専攻'),(SELECT admin_id FROM admin_tbl where name='青柳　孝浩'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='ゲーム・ＣＧ・アニメ専攻科 ＣＧ専攻'),(SELECT admin_id FROM admin_tbl where name='田熊　秀一郎'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='ゲーム・ＣＧ・アニメ専攻科 ＣＧ専攻'),(SELECT admin_id FROM admin_tbl where name='甲斐　奈津代'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='ゲーム・ＣＧ・アニメ科 ゲームコース'),(SELECT admin_id FROM admin_tbl where name='岡本　光弘'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='ゲーム・ＣＧ・アニメ科 ゲームコース'),(SELECT admin_id FROM admin_tbl where name='末金　誠一'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='ゲーム・ＣＧ・アニメ科 ＣＧコース'),(SELECT admin_id FROM admin_tbl where name='藤村　海妙'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='ゲーム・ＣＧ・アニメ科 ＣＧコース'),(SELECT admin_id FROM admin_tbl where name='甲斐　奈津代'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='ゲーム・ＣＧ・アニメ科 アニメコース'),(SELECT admin_id FROM admin_tbl where name='坂本　真来'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='ゲーム・ＣＧ・アニメ科 アニメコース'),(SELECT admin_id FROM admin_tbl where name='岩村　剛士'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='ゲーム・ＣＧ専攻科 ゲーム専攻'),(SELECT admin_id FROM admin_tbl where name='髙木 秀信'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='ゲーム・ＣＧ専攻科 ＣＧ専攻'),(SELECT admin_id FROM admin_tbl where name='田熊　秀一郎'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='マンガ・イラスト科 マンガコース'),(SELECT admin_id FROM admin_tbl where name='山下　愛里彩'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='マンガ・イラスト科 イラストコース'),(SELECT admin_id FROM admin_tbl where name='上野　哲史'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='ゲーム専攻科'),(SELECT admin_id FROM admin_tbl where name='山﨑　芳英'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='ゲーム学科'),(SELECT admin_id FROM admin_tbl where name='高木　慎一'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'A',(SELECT department_id FROM department_tbl where name='ＣＧ専攻科'),(SELECT admin_id FROM admin_tbl where name='久澤　謙二郎'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'B',(SELECT department_id FROM department_tbl where name='ＣＧ専攻科'),(SELECT admin_id FROM admin_tbl where name='清山　忠相'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='ＣＧ学科'),(SELECT admin_id FROM admin_tbl where name='原田　英一'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'A',(SELECT department_id FROM department_tbl where name='アニメ学科'),(SELECT admin_id FROM admin_tbl where name='久澤　謙二郎'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'B',(SELECT department_id FROM department_tbl where name='アニメ学科'),(SELECT admin_id FROM admin_tbl where name='清山　忠相'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='コミックイラスト科　アニメコース'),(SELECT admin_id FROM admin_tbl where name='坂本　真来'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'A',(SELECT department_id FROM department_tbl where name='マンガ学科'),(SELECT admin_id FROM admin_tbl where name='久澤　謙二郎'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='コミックイラスト科　マンガコース'),(SELECT admin_id FROM admin_tbl where name='羽月　由憲'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'A',(SELECT department_id FROM department_tbl where name='イラスト学科'),(SELECT admin_id FROM admin_tbl where name='久澤　謙二郎'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'B',(SELECT department_id FROM department_tbl where name='イラスト学科'),(SELECT admin_id FROM admin_tbl where name='清山　忠相'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='コミックイラスト科　イラストコース'),(SELECT admin_id FROM admin_tbl where name='徳永　靖之'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='コミックイラスト研究科'),(SELECT admin_id FROM admin_tbl where name='上野　哲史'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='情報システムコース'),(SELECT admin_id FROM admin_tbl where name='古木　鷹人'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='情報システムコース'),(SELECT admin_id FROM admin_tbl where name='赤城　潤一'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='情報システムコース'),(SELECT admin_id FROM admin_tbl where name='竹並　真理恵'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='ゲームクリエイターコース'),(SELECT admin_id FROM admin_tbl where name='古木　鷹人'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='ゲームクリエイターコース'),(SELECT admin_id FROM admin_tbl where name='赤城　潤一'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='ゲームクリエイターコース'),(SELECT admin_id FROM admin_tbl where name='竹並　真理恵'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='CG・イラストコース'),(SELECT admin_id FROM admin_tbl where name='古木　鷹人'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='CG・イラストコース'),(SELECT admin_id FROM admin_tbl where name='赤城　潤一'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='CG・イラストコース'),(SELECT admin_id FROM admin_tbl where name='竹並　真理恵'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='システムナレッジコース'),(SELECT admin_id FROM admin_tbl where name='古木　鷹人'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='システムナレッジコース'),(SELECT admin_id FROM admin_tbl where name='赤城　潤一'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='ゲームナレッジコース'),(SELECT admin_id FROM admin_tbl where name='古木　鷹人'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='ゲームナレッジコース'),(SELECT admin_id FROM admin_tbl where name='竹並　真理恵'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='イラストナレッジコース'),(SELECT admin_id FROM admin_tbl where name='古木　鷹人'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='イラストナレッジコース'),(SELECT admin_id FROM admin_tbl where name='赤城　潤一'));
INSERT INTO `class_tbl`(`class_id`, `name`, `department_id`, `admin_id`) VALUES (null,'',(SELECT department_id FROM department_tbl where name='イラストナレッジコース'),(SELECT admin_id FROM admin_tbl where name='竹並　真理恵'));

INSERT INTO industry_tbl (industry_id, name) VALUES (NULL,'医療系');
INSERT INTO industry_tbl (industry_id, name) VALUES (NULL,'事務系');
INSERT INTO industry_tbl (industry_id, name) VALUES (NULL,'IT系');
INSERT INTO industry_tbl (industry_id, name) VALUES (NULL,'工業系');
INSERT INTO industry_tbl (industry_id, name) VALUES (NULL,'製造系');
INSERT INTO industry_tbl (industry_id, name) VALUES (NULL,'営業系');
INSERT INTO industry_tbl (industry_id, name) VALUES (NULL,'デザイン系');
INSERT INTO industry_tbl (industry_id, name) VALUES (NULL,'福祉系');
INSERT INTO industry_tbl (industry_id, name) VALUES (NULL,'サービス系');
INSERT INTO industry_tbl (industry_id, name) VALUES (NULL,'美容系');
INSERT INTO industry_tbl (industry_id, name) VALUES (NULL,'自動車系');

INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'理学療法士',(SELECT industry_id FROM industry_tbl WHERE name='医療系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'作業療法士',(SELECT industry_id FROM industry_tbl WHERE name='医療系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'言語聴覚士',(SELECT industry_id FROM industry_tbl WHERE name='医療系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'医療事務',(SELECT industry_id FROM industry_tbl WHERE name='事務系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'医師事務作業補助者',(SELECT industry_id FROM industry_tbl WHERE name='事務系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'調剤事務',(SELECT industry_id FROM industry_tbl WHERE name='事務系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'診療情報管理職',(SELECT industry_id FROM industry_tbl WHERE name='事務系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'歯科受付助手',(SELECT industry_id FROM industry_tbl WHERE name='事務系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'病棟クラーク',(SELECT industry_id FROM industry_tbl WHERE name='事務系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'ＳＥ',(SELECT industry_id FROM industry_tbl WHERE name='IT系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'プログラマ',(SELECT industry_id FROM industry_tbl WHERE name='IT系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'運用オペレータ',(SELECT industry_id FROM industry_tbl WHERE name='IT系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'ＣＧデザイナー',(SELECT industry_id FROM industry_tbl WHERE name='IT系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'ネットワーク関係',(SELECT industry_id FROM industry_tbl WHERE name='IT系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'カスタマエンジニア',(SELECT industry_id FROM industry_tbl WHERE name='IT系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'ゲームプログラマ',(SELECT industry_id FROM industry_tbl WHERE name='IT系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'ゲームプランナ',(SELECT industry_id FROM industry_tbl WHERE name='IT系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'サーバーエンジニア',(SELECT industry_id FROM industry_tbl WHERE name='IT系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'カスタマサポート',(SELECT industry_id FROM industry_tbl WHERE name='IT系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'デバッガー',(SELECT industry_id FROM industry_tbl WHERE name='IT系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'検証テストエンジニア',(SELECT industry_id FROM industry_tbl WHERE name='IT系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'制御関係',(SELECT industry_id FROM industry_tbl WHERE name='工業系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'ＣＧ関係',(SELECT industry_id FROM industry_tbl WHERE name='工業系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'ＣＡＤ',(SELECT industry_id FROM industry_tbl WHERE name='工業系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'設計職',(SELECT industry_id FROM industry_tbl WHERE name='工業系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'施工管理',(SELECT industry_id FROM industry_tbl WHERE name='工業系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'現業職',(SELECT industry_id FROM industry_tbl WHERE name='工業系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'積算職',(SELECT industry_id FROM industry_tbl WHERE name='工業系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'建物管理',(SELECT industry_id FROM industry_tbl WHERE name='工業系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'建築系営業職',(SELECT industry_id FROM industry_tbl WHERE name='工業系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'建築系総合職',(SELECT industry_id FROM industry_tbl WHERE name='工業系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'補償コンサルタント',(SELECT industry_id FROM industry_tbl WHERE name='工業系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'一般事務',(SELECT industry_id FROM industry_tbl WHERE name='事務系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'経理事務',(SELECT industry_id FROM industry_tbl WHERE name='事務系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'営業事務',(SELECT industry_id FROM industry_tbl WHERE name='事務系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'総務事務',(SELECT industry_id FROM industry_tbl WHERE name='事務系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'貿易事務',(SELECT industry_id FROM industry_tbl WHERE name='事務系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'事務系総合職',(SELECT industry_id FROM industry_tbl WHERE name='事務系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'秘書',(SELECT industry_id FROM industry_tbl WHERE name='事務系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'税理士補助',(SELECT industry_id FROM industry_tbl WHERE name='事務系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'コールセンター職',(SELECT industry_id FROM industry_tbl WHERE name='事務系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'入力オペレータ',(SELECT industry_id FROM industry_tbl WHERE name='事務系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'翻訳通訳',(SELECT industry_id FROM industry_tbl WHERE name='事務系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'現業職',(SELECT industry_id FROM industry_tbl WHERE name='製造系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'営業職',(SELECT industry_id FROM industry_tbl WHERE name='営業系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'販売職',(SELECT industry_id FROM industry_tbl WHERE name='営業系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'インストラクタ',(SELECT industry_id FROM industry_tbl WHERE name='営業系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'営業企画職',(SELECT industry_id FROM industry_tbl WHERE name='営業系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'サービス',(SELECT industry_id FROM industry_tbl WHERE name='営業系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'総合職',(SELECT industry_id FROM industry_tbl WHERE name='営業系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'警備',(SELECT industry_id FROM industry_tbl WHERE name='営業系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'デザイナー',(SELECT industry_id FROM industry_tbl WHERE name='デザイン系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'ＤＴＰオペレータ',(SELECT industry_id FROM industry_tbl WHERE name='デザイン系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'インテリア関係',(SELECT industry_id FROM industry_tbl WHERE name='デザイン系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'Ｗｅｂデザイナー',(SELECT industry_id FROM industry_tbl WHERE name='デザイン系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'制作技術',(SELECT industry_id FROM industry_tbl WHERE name='デザイン系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'アニメーター',(SELECT industry_id FROM industry_tbl WHERE name='デザイン系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'漫画家',(SELECT industry_id FROM industry_tbl WHERE name='デザイン系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'ディレクター',(SELECT industry_id FROM industry_tbl WHERE name='デザイン系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'企画',(SELECT industry_id FROM industry_tbl WHERE name='デザイン系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'編集',(SELECT industry_id FROM industry_tbl WHERE name='デザイン系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'イラストレーター',(SELECT industry_id FROM industry_tbl WHERE name='デザイン系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'制作進行',(SELECT industry_id FROM industry_tbl WHERE name='デザイン系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'撮影',(SELECT industry_id FROM industry_tbl WHERE name='デザイン系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'介護職',(SELECT industry_id FROM industry_tbl WHERE name='福祉系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'支援員',(SELECT industry_id FROM industry_tbl WHERE name='福祉系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'保育士',(SELECT industry_id FROM industry_tbl WHERE name='福祉系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'教諭',(SELECT industry_id FROM industry_tbl WHERE name='福祉系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'看護助手',(SELECT industry_id FROM industry_tbl WHERE name='福祉系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'精神保健福祉士',(SELECT industry_id FROM industry_tbl WHERE name='福祉系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'相談員',(SELECT industry_id FROM industry_tbl WHERE name='福祉系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'メディカルソーシャルワーカー',(SELECT industry_id FROM industry_tbl WHERE name='福祉系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'児童指導員',(SELECT industry_id FROM industry_tbl WHERE name='福祉系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'一般サービス',(SELECT industry_id FROM industry_tbl WHERE name='サービス系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'メディカルアテンダント',(SELECT industry_id FROM industry_tbl WHERE name='サービス系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'ブライダル関係',(SELECT industry_id FROM industry_tbl WHERE name='サービス系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'航空関係',(SELECT industry_id FROM industry_tbl WHERE name='サービス系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'ホテル関係',(SELECT industry_id FROM industry_tbl WHERE name='サービス系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'旅行関係',(SELECT industry_id FROM industry_tbl WHERE name='サービス系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'鉄道関係',(SELECT industry_id FROM industry_tbl WHERE name='サービス系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'パティシエ',(SELECT industry_id FROM industry_tbl WHERE name='サービス系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'調理',(SELECT industry_id FROM industry_tbl WHERE name='サービス系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'フォトグラファー',(SELECT industry_id FROM industry_tbl WHERE name='サービス系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'アイリスト',(SELECT industry_id FROM industry_tbl WHERE name='美容系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'セラピスト',(SELECT industry_id FROM industry_tbl WHERE name='美容系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'美容師',(SELECT industry_id FROM industry_tbl WHERE name='美容系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'エステティシャン',(SELECT industry_id FROM industry_tbl WHERE name='美容系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'美容部員',(SELECT industry_id FROM industry_tbl WHERE name='美容系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'ネイリスト',(SELECT industry_id FROM industry_tbl WHERE name='美容系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'メイクアップアーティスト',(SELECT industry_id FROM industry_tbl WHERE name='美容系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'ヘアメイク',(SELECT industry_id FROM industry_tbl WHERE name='美容系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'カラーリスト',(SELECT industry_id FROM industry_tbl WHERE name='美容系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'ブライダル',(SELECT industry_id FROM industry_tbl WHERE name='美容系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'スパニスト',(SELECT industry_id FROM industry_tbl WHERE name='美容系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'ケアリスト',(SELECT industry_id FROM industry_tbl WHERE name='美容系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'ビューティコーディネーター',(SELECT industry_id FROM industry_tbl WHERE name='美容系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'フェイシャリスト',(SELECT industry_id FROM industry_tbl WHERE name='美容系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'スキンケアアドバイザー',(SELECT industry_id FROM industry_tbl WHERE name='美容系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'整体',(SELECT industry_id FROM industry_tbl WHERE name='美容系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'レセプショニスト',(SELECT industry_id FROM industry_tbl WHERE name='美容系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'整備士',(SELECT industry_id FROM industry_tbl WHERE name='自動車系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'検査員',(SELECT industry_id FROM industry_tbl WHERE name='自動車系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'技術アジャスター',(SELECT industry_id FROM industry_tbl WHERE name='自動車系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'機械設計職',(SELECT industry_id FROM industry_tbl WHERE name='自動車系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'技術職',(SELECT industry_id FROM industry_tbl WHERE name='自動車系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'技能職',(SELECT industry_id FROM industry_tbl WHERE name='自動車系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'板金塗装',(SELECT industry_id FROM industry_tbl WHERE name='自動車系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'現業職',(SELECT industry_id FROM industry_tbl WHERE name='自動車系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'評価・開発',(SELECT industry_id FROM industry_tbl WHERE name='自動車系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'総合職',(SELECT industry_id FROM industry_tbl WHERE name='自動車系'));
INSERT INTO `industrykind_tbl`(`industrykind_id`, `name`, `industry_id`) VALUES (NULL,'オフィス技能職',(SELECT industry_id FROM industry_tbl WHERE name='自動車系'));

INSERT INTO `recrutiment_type_tbl`(`recrutiment_type_id`, `name`) VALUES (null,'併願可');
INSERT INTO `recrutiment_type_tbl`(`recrutiment_type_id`, `name`) VALUES (null,'専願');
INSERT INTO `recrutiment_type_tbl`(`recrutiment_type_id`, `name`) VALUES (null,'オープン');

INSERT INTO `jobhunting_status_tbl` (`jobhunting_status_id`, `name`) VALUES (NULL, '進路決定済み');
INSERT INTO `student_tbl` (`student_id`, `password`, `student_no`, `name`, `mail`, `class_id`, `jobhunting_status_id`, `image`, `tel`, `address`, `year`, `c_trust`, `c_entrapment`, `c_objectivity`, `c_physicality`, `c_moodiness`, `c_persistence`, `c_regularity`, `c_competitiveness`, `c_selfesteem`, `c_prudence`, `c_bearishness`, `c_surroundings`, `c_science`, `c_society`, `c_psychology`, `c_art`, `c_positivity`, `c_cooperativeness`, `c_responsibility`, `c_reliability`, `c_leadership`, `c_empathy`, `c_emotional_stability`, `c_obedience`, `c_autonomy`, `c_moratorium`, `c_desire_success`, `c_affinity`, `c_seeking`, `c_manifestation`, `c_order`, `c_material`, `c_crisis_resistance`, `c_independence`, `c_control`, `c_workethic`, `c_active`, `c_enthusiasm`, `c_perseverance`, `c_responsibility2`, `c_decisive`, `c_leadership2`, `c_leader`, `c_selftrust`, `c_adjustment`, `c_negotiation`, `c_innovative`, `c_analysis`, `c_Insight`, `c_planning`, `c_expertise`, `c_utilization`, `c_general`, `c_mental`, `c_legwaist`, `c_concentration`, `c_standardization`, `c_range`, `c_established`, `c_typejudge`) VALUES (NULL, '387a0051226be0d20927b2c0bb46becd', '0000001', '西野直幸', 'nishino@s.asojuku.ac.jp', '1', '1', 'noimage.png', '1', '福岡市', '2022', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `admin_tbl` (`admin_id`, `name`, `mail`, `password`, `image`, `role_id`) VALUES
(NULL, '西野直幸', 'nishino@asojuku.ac.jp', '0b8b3f1d7f7dca255b216eb22ec576ab', '', 1);