package jp.ac.asojuku.jobhuntingsystem.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 管理者テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class AdminTbl implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** admin_id. */
	private Integer adminId;

	/** name. */
	private String name;

	/** mail. */
	private String mail;

	/** password. */
	private String password;

	/** image. */
	private String image;

	/** role_id. */
	private Integer roleId;

	/** 学科テーブル 一覧. */
	private Set<ClassTbl> classTblSet;

	/**
	 * コンストラクタ.
	 */
	public AdminTbl() {
		this.classTblSet = new HashSet<ClassTbl>();
	}

	/**
	 * admin_id を設定します.
	 * 
	 * @param adminId
	 *            admin_id
	 */
	public void setAdminId(Integer adminId) {
		this.adminId = adminId;
	}

	/**
	 * admin_id を取得します.
	 * 
	 * @return admin_id
	 */
	public Integer getAdminId() {
		return this.adminId;
	}

	/**
	 * name を設定します.
	 * 
	 * @param name
	 *            name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * name を取得します.
	 * 
	 * @return name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * mail を設定します.
	 * 
	 * @param mail
	 *            mail
	 */
	public void setMail(String mail) {
		this.mail = mail;
	}

	/**
	 * mail を取得します.
	 * 
	 * @return mail
	 */
	public String getMail() {
		return this.mail;
	}

	/**
	 * password を設定します.
	 * 
	 * @param password
	 *            password
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * password を取得します.
	 * 
	 * @return password
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * image を設定します.
	 * 
	 * @param image
	 *            image
	 */
	public void setImage(String image) {
		this.image = image;
	}

	/**
	 * image を取得します.
	 * 
	 * @return image
	 */
	public String getImage() {
		return this.image;
	}

	/**
	 * role_id を設定します.
	 * 
	 * @param roleId
	 *            role_id
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * role_id を取得します.
	 * 
	 * @return role_id
	 */
	public Integer getRoleId() {
		return this.roleId;
	}

	/**
	 * 学科テーブル 一覧を設定します.
	 * 
	 * @param classTblSet
	 *            学科テーブル 一覧
	 */
	public void setClassTblSet(Set<ClassTbl> classTblSet) {
		this.classTblSet = classTblSet;
	}

	/**
	 * 学科テーブル を追加します.
	 * 
	 * @param classTbl
	 *            学科テーブル
	 */
	public void addClassTbl(ClassTbl classTbl) {
		this.classTblSet.add(classTbl);
	}

	/**
	 * 学科テーブル 一覧を取得します.
	 * 
	 * @return 学科テーブル 一覧
	 */
	public Set<ClassTbl> getClassTblSet() {
		return this.classTblSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((adminId == null) ? 0 : adminId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		AdminTbl other = (AdminTbl) obj;
		if (adminId == null) {
			if (other.adminId != null) {
				return false;
			}
		} else if (!adminId.equals(other.adminId)) {
			return false;
		}
		return true;
	}

}
