package jp.ac.asojuku.jobhuntingsystem.entity;

import java.io.Serializable;

/**
 * 進路決定テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CareerReportTbl implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** career_report_id. */
	private Integer careerReportId;

	/** 学生テーブル. */
	private StudentTbl studentNostudentTbl;

	/**
	 * コンストラクタ.
	 */
	public CareerReportTbl() {
	}

	/**
	 * career_report_id を設定します.
	 * 
	 * @param careerReportId
	 *            career_report_id
	 */
	public void setCareerReportId(Integer careerReportId) {
		this.careerReportId = careerReportId;
	}

	/**
	 * career_report_id を取得します.
	 * 
	 * @return career_report_id
	 */
	public Integer getCareerReportId() {
		return this.careerReportId;
	}

	/**
	 * 学生テーブル を設定します.
	 * 
	 * @param studentNostudentTbl
	 *            学生テーブル
	 */
	public void setStudentNostudentTbl(StudentTbl studentNostudentTbl) {
		this.studentNostudentTbl = studentNostudentTbl;
	}

	/**
	 * 学生テーブル を取得します.
	 * 
	 * @return 学生テーブル
	 */
	public StudentTbl getStudentNostudentTbl() {
		return this.studentNostudentTbl;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((careerReportId == null) ? 0 : careerReportId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		CareerReportTbl other = (CareerReportTbl) obj;
		if (careerReportId == null) {
			if (other.careerReportId != null) {
				return false;
			}
		} else if (!careerReportId.equals(other.careerReportId)) {
			return false;
		}
		return true;
	}

}
