package jp.ac.asojuku.jobhuntingsystem.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 学科テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ClassTbl implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** class_id. */
	private Integer classId;

	/** name. */
	private String name;

	/** 学科テーブル. */
	private DepartmentTbl departmentTbl;

	/** 管理者テーブル. */
	private AdminTbl adminTbl;

	/** 学生テーブル 一覧. */
	private Set<StudentTbl> studentTblSet;

	/**
	 * コンストラクタ.
	 */
	public ClassTbl() {
		this.studentTblSet = new HashSet<StudentTbl>();
	}

	/**
	 * class_id を設定します.
	 * 
	 * @param classId
	 *            class_id
	 */
	public void setClassId(Integer classId) {
		this.classId = classId;
	}

	/**
	 * class_id を取得します.
	 * 
	 * @return class_id
	 */
	public Integer getClassId() {
		return this.classId;
	}

	/**
	 * name を設定します.
	 * 
	 * @param name
	 *            name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * name を取得します.
	 * 
	 * @return name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * 学科テーブル を設定します.
	 * 
	 * @param departmentTbl
	 *            学科テーブル
	 */
	public void setDepartmentTbl(DepartmentTbl departmentTbl) {
		this.departmentTbl = departmentTbl;
	}

	/**
	 * 学科テーブル を取得します.
	 * 
	 * @return 学科テーブル
	 */
	public DepartmentTbl getDepartmentTbl() {
		return this.departmentTbl;
	}

	/**
	 * 管理者テーブル を設定します.
	 * 
	 * @param adminTbl
	 *            管理者テーブル
	 */
	public void setAdminTbl(AdminTbl adminTbl) {
		this.adminTbl = adminTbl;
	}

	/**
	 * 管理者テーブル を取得します.
	 * 
	 * @return 管理者テーブル
	 */
	public AdminTbl getAdminTbl() {
		return this.adminTbl;
	}

	/**
	 * 学生テーブル 一覧を設定します.
	 * 
	 * @param studentTblSet
	 *            学生テーブル 一覧
	 */
	public void setStudentTblSet(Set<StudentTbl> studentTblSet) {
		this.studentTblSet = studentTblSet;
	}

	/**
	 * 学生テーブル を追加します.
	 * 
	 * @param studentTbl
	 *            学生テーブル
	 */
	public void addStudentTbl(StudentTbl studentTbl) {
		this.studentTblSet.add(studentTbl);
	}

	/**
	 * 学生テーブル 一覧を取得します.
	 * 
	 * @return 学生テーブル 一覧
	 */
	public Set<StudentTbl> getStudentTblSet() {
		return this.studentTblSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((classId == null) ? 0 : classId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ClassTbl other = (ClassTbl) obj;
		if (classId == null) {
			if (other.classId != null) {
				return false;
			}
		} else if (!classId.equals(other.classId)) {
			return false;
		}
		return true;
	}

}
