package jp.ac.asojuku.jobhuntingsystem.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 企業テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CompanyTbl implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** company_id. */
	private Integer companyId;

	/** name. */
	private String name;

	/** furigana. */
	private String furigana;

	/** address. */
	private String address;

	/** code. */
	private String code;

	/** capital. */
	private Integer capital;

	/** establishment. */
	private Integer establishment;

	/** annualsales. */
	private Integer annualsales;

	/** url. */
	private String url;

	/** password. */
	private String password;

	/** pic. */
	private String pic;

	/** moc. */
	private String moc;

	/** toc. */
	private String toc;

	/** 企業業種テーブル 一覧. */
	private Set<CompanyIndustry> companyIndustrySet;

	/** イベントテーブル 一覧. */
	private Set<EventTbl> eventTblSet;

	/** お気に入りテーブル 一覧. */
	private Set<FavoritTbl> favoritTblSet;

	/** 学生テーブル 一覧. */
	private Set<GraduateTbl> graduateTblSet;

	/** 採用求人テーブル 一覧. */
	private Set<RecruitmentTbl> recruitmentTblSet;

	/**
	 * コンストラクタ.
	 */
	public CompanyTbl() {
		this.companyIndustrySet = new HashSet<CompanyIndustry>();
		this.eventTblSet = new HashSet<EventTbl>();
		this.favoritTblSet = new HashSet<FavoritTbl>();
		this.graduateTblSet = new HashSet<GraduateTbl>();
		this.recruitmentTblSet = new HashSet<RecruitmentTbl>();
	}

	/**
	 * company_id を設定します.
	 * 
	 * @param companyId
	 *            company_id
	 */
	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	/**
	 * company_id を取得します.
	 * 
	 * @return company_id
	 */
	public Integer getCompanyId() {
		return this.companyId;
	}

	/**
	 * name を設定します.
	 * 
	 * @param name
	 *            name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * name を取得します.
	 * 
	 * @return name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * furigana を設定します.
	 * 
	 * @param furigana
	 *            furigana
	 */
	public void setFurigana(String furigana) {
		this.furigana = furigana;
	}

	/**
	 * furigana を取得します.
	 * 
	 * @return furigana
	 */
	public String getFurigana() {
		return this.furigana;
	}

	/**
	 * address を設定します.
	 * 
	 * @param address
	 *            address
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * address を取得します.
	 * 
	 * @return address
	 */
	public String getAddress() {
		return this.address;
	}

	/**
	 * code を設定します.
	 * 
	 * @param code
	 *            code
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * code を取得します.
	 * 
	 * @return code
	 */
	public String getCode() {
		return this.code;
	}

	/**
	 * capital を設定します.
	 * 
	 * @param capital
	 *            capital
	 */
	public void setCapital(Integer capital) {
		this.capital = capital;
	}

	/**
	 * capital を取得します.
	 * 
	 * @return capital
	 */
	public Integer getCapital() {
		return this.capital;
	}

	/**
	 * establishment を設定します.
	 * 
	 * @param establishment
	 *            establishment
	 */
	public void setEstablishment(Integer establishment) {
		this.establishment = establishment;
	}

	/**
	 * establishment を取得します.
	 * 
	 * @return establishment
	 */
	public Integer getEstablishment() {
		return this.establishment;
	}

	/**
	 * annualsales を設定します.
	 * 
	 * @param annualsales
	 *            annualsales
	 */
	public void setAnnualsales(Integer annualsales) {
		this.annualsales = annualsales;
	}

	/**
	 * annualsales を取得します.
	 * 
	 * @return annualsales
	 */
	public Integer getAnnualsales() {
		return this.annualsales;
	}

	/**
	 * url を設定します.
	 * 
	 * @param url
	 *            url
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * url を取得します.
	 * 
	 * @return url
	 */
	public String getUrl() {
		return this.url;
	}

	/**
	 * password を設定します.
	 * 
	 * @param password
	 *            password
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * password を取得します.
	 * 
	 * @return password
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * pic を設定します.
	 * 
	 * @param pic
	 *            pic
	 */
	public void setPic(String pic) {
		this.pic = pic;
	}

	/**
	 * pic を取得します.
	 * 
	 * @return pic
	 */
	public String getPic() {
		return this.pic;
	}

	/**
	 * moc を設定します.
	 * 
	 * @param moc
	 *            moc
	 */
	public void setMoc(String moc) {
		this.moc = moc;
	}

	/**
	 * moc を取得します.
	 * 
	 * @return moc
	 */
	public String getMoc() {
		return this.moc;
	}

	/**
	 * toc を設定します.
	 * 
	 * @param toc
	 *            toc
	 */
	public void setToc(String toc) {
		this.toc = toc;
	}

	/**
	 * toc を取得します.
	 * 
	 * @return toc
	 */
	public String getToc() {
		return this.toc;
	}

	/**
	 * 企業業種テーブル 一覧を設定します.
	 * 
	 * @param companyIndustrySet
	 *            企業業種テーブル 一覧
	 */
	public void setCompanyIndustrySet(Set<CompanyIndustry> companyIndustrySet) {
		this.companyIndustrySet = companyIndustrySet;
	}

	/**
	 * 企業業種テーブル を追加します.
	 * 
	 * @param companyIndustry
	 *            企業業種テーブル
	 */
	public void addCompanyIndustry(CompanyIndustry companyIndustry) {
		this.companyIndustrySet.add(companyIndustry);
	}

	/**
	 * 企業業種テーブル 一覧を取得します.
	 * 
	 * @return 企業業種テーブル 一覧
	 */
	public Set<CompanyIndustry> getCompanyIndustrySet() {
		return this.companyIndustrySet;
	}

	/**
	 * イベントテーブル 一覧を設定します.
	 * 
	 * @param eventTblSet
	 *            イベントテーブル 一覧
	 */
	public void setEventTblSet(Set<EventTbl> eventTblSet) {
		this.eventTblSet = eventTblSet;
	}

	/**
	 * イベントテーブル を追加します.
	 * 
	 * @param eventTbl
	 *            イベントテーブル
	 */
	public void addEventTbl(EventTbl eventTbl) {
		this.eventTblSet.add(eventTbl);
	}

	/**
	 * イベントテーブル 一覧を取得します.
	 * 
	 * @return イベントテーブル 一覧
	 */
	public Set<EventTbl> getEventTblSet() {
		return this.eventTblSet;
	}

	/**
	 * お気に入りテーブル 一覧を設定します.
	 * 
	 * @param favoritTblSet
	 *            お気に入りテーブル 一覧
	 */
	public void setFavoritTblSet(Set<FavoritTbl> favoritTblSet) {
		this.favoritTblSet = favoritTblSet;
	}

	/**
	 * お気に入りテーブル を追加します.
	 * 
	 * @param favoritTbl
	 *            お気に入りテーブル
	 */
	public void addFavoritTbl(FavoritTbl favoritTbl) {
		this.favoritTblSet.add(favoritTbl);
	}

	/**
	 * お気に入りテーブル 一覧を取得します.
	 * 
	 * @return お気に入りテーブル 一覧
	 */
	public Set<FavoritTbl> getFavoritTblSet() {
		return this.favoritTblSet;
	}

	/**
	 * 学生テーブル 一覧を設定します.
	 * 
	 * @param graduateTblSet
	 *            学生テーブル 一覧
	 */
	public void setGraduateTblSet(Set<GraduateTbl> graduateTblSet) {
		this.graduateTblSet = graduateTblSet;
	}

	/**
	 * 学生テーブル を追加します.
	 * 
	 * @param graduateTbl
	 *            学生テーブル
	 */
	public void addGraduateTbl(GraduateTbl graduateTbl) {
		this.graduateTblSet.add(graduateTbl);
	}

	/**
	 * 学生テーブル 一覧を取得します.
	 * 
	 * @return 学生テーブル 一覧
	 */
	public Set<GraduateTbl> getGraduateTblSet() {
		return this.graduateTblSet;
	}

	/**
	 * 採用求人テーブル 一覧を設定します.
	 * 
	 * @param recruitmentTblSet
	 *            採用求人テーブル 一覧
	 */
	public void setRecruitmentTblSet(Set<RecruitmentTbl> recruitmentTblSet) {
		this.recruitmentTblSet = recruitmentTblSet;
	}

	/**
	 * 採用求人テーブル を追加します.
	 * 
	 * @param recruitmentTbl
	 *            採用求人テーブル
	 */
	public void addRecruitmentTbl(RecruitmentTbl recruitmentTbl) {
		this.recruitmentTblSet.add(recruitmentTbl);
	}

	/**
	 * 採用求人テーブル 一覧を取得します.
	 * 
	 * @return 採用求人テーブル 一覧
	 */
	public Set<RecruitmentTbl> getRecruitmentTblSet() {
		return this.recruitmentTblSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((companyId == null) ? 0 : companyId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		CompanyTbl other = (CompanyTbl) obj;
		if (companyId == null) {
			if (other.companyId != null) {
				return false;
			}
		} else if (!companyId.equals(other.companyId)) {
			return false;
		}
		return true;
	}

}
