package jp.ac.asojuku.jobhuntingsystem.entity;

import java.io.Serializable;

/**
 * 企業業種テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CompanyIndustry implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ci_id. */
	private Integer ciId;

	/** 企業テーブル. */
	private CompanyTbl companyTbl;

	/** 業種テーブル. */
	private IndustrykindTbl industrykindTbl;

	/**
	 * コンストラクタ.
	 */
	public CompanyIndustry() {
	}

	/**
	 * ci_id を設定します.
	 * 
	 * @param ciId
	 *            ci_id
	 */
	public void setCiId(Integer ciId) {
		this.ciId = ciId;
	}

	/**
	 * ci_id を取得します.
	 * 
	 * @return ci_id
	 */
	public Integer getCiId() {
		return this.ciId;
	}

	/**
	 * 企業テーブル を設定します.
	 * 
	 * @param companyTbl
	 *            企業テーブル
	 */
	public void setCompanyTbl(CompanyTbl companyTbl) {
		this.companyTbl = companyTbl;
	}

	/**
	 * 企業テーブル を取得します.
	 * 
	 * @return 企業テーブル
	 */
	public CompanyTbl getCompanyTbl() {
		return this.companyTbl;
	}

	/**
	 * 業種テーブル を設定します.
	 * 
	 * @param industrykindTbl
	 *            業種テーブル
	 */
	public void setIndustrykindTbl(IndustrykindTbl industrykindTbl) {
		this.industrykindTbl = industrykindTbl;
	}

	/**
	 * 業種テーブル を取得します.
	 * 
	 * @return 業種テーブル
	 */
	public IndustrykindTbl getIndustrykindTbl() {
		return this.industrykindTbl;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((ciId == null) ? 0 : ciId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		CompanyIndustry other = (CompanyIndustry) obj;
		if (ciId == null) {
			if (other.ciId != null) {
				return false;
			}
		} else if (!ciId.equals(other.ciId)) {
			return false;
		}
		return true;
	}

}
