package jp.ac.asojuku.jobhuntingsystem.entity;

import java.io.Serializable;

/**
 * 企業業種テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CompanyIndustry implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 企業テーブル. */
	private CompanyTbl companyTbl;

	/** 業種テーブル. */
	private IndustrykindTbl industrykindTbl;

	/**
	 * コンストラクタ.
	 */
	public CompanyIndustry() {
	}

	/**
	 * 企業テーブル を設定します.
	 * 
	 * @param companyTbl
	 *            企業テーブル
	 */
	public void setCompanyTbl(CompanyTbl companyTbl) {
		this.companyTbl = companyTbl;
	}

	/**
	 * 企業テーブル を取得します.
	 * 
	 * @return 企業テーブル
	 */
	public CompanyTbl getCompanyTbl() {
		return this.companyTbl;
	}

	/**
	 * 業種テーブル を設定します.
	 * 
	 * @param industrykindTbl
	 *            業種テーブル
	 */
	public void setIndustrykindTbl(IndustrykindTbl industrykindTbl) {
		this.industrykindTbl = industrykindTbl;
	}

	/**
	 * 業種テーブル を取得します.
	 * 
	 * @return 業種テーブル
	 */
	public IndustrykindTbl getIndustrykindTbl() {
		return this.industrykindTbl;
	}


}
