package jp.ac.asojuku.jobhuntingsystem.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 学科テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class DepartmentTbl implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** department_id. */
	private Integer departmentId;

	/** name. */
	private String name;

	/** 学校テーブル. */
	private SchoolTbl schoolTbl;

	/** 学科テーブル 一覧. */
	private Set<ClassTbl> classTblSet;

	/**
	 * コンストラクタ.
	 */
	public DepartmentTbl() {
		this.classTblSet = new HashSet<ClassTbl>();
	}

	/**
	 * department_id を設定します.
	 * 
	 * @param departmentId
	 *            department_id
	 */
	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	/**
	 * department_id を取得します.
	 * 
	 * @return department_id
	 */
	public Integer getDepartmentId() {
		return this.departmentId;
	}

	/**
	 * name を設定します.
	 * 
	 * @param name
	 *            name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * name を取得します.
	 * 
	 * @return name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * 学校テーブル を設定します.
	 * 
	 * @param schoolTbl
	 *            学校テーブル
	 */
	public void setSchoolTbl(SchoolTbl schoolTbl) {
		this.schoolTbl = schoolTbl;
	}

	/**
	 * 学校テーブル を取得します.
	 * 
	 * @return 学校テーブル
	 */
	public SchoolTbl getSchoolTbl() {
		return this.schoolTbl;
	}

	/**
	 * 学科テーブル 一覧を設定します.
	 * 
	 * @param classTblSet
	 *            学科テーブル 一覧
	 */
	public void setClassTblSet(Set<ClassTbl> classTblSet) {
		this.classTblSet = classTblSet;
	}

	/**
	 * 学科テーブル を追加します.
	 * 
	 * @param classTbl
	 *            学科テーブル
	 */
	public void addClassTbl(ClassTbl classTbl) {
		this.classTblSet.add(classTbl);
	}

	/**
	 * 学科テーブル 一覧を取得します.
	 * 
	 * @return 学科テーブル 一覧
	 */
	public Set<ClassTbl> getClassTblSet() {
		return this.classTblSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((departmentId == null) ? 0 : departmentId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		DepartmentTbl other = (DepartmentTbl) obj;
		if (departmentId == null) {
			if (other.departmentId != null) {
				return false;
			}
		} else if (!departmentId.equals(other.departmentId)) {
			return false;
		}
		return true;
	}

}
