package jp.ac.asojuku.jobhuntingsystem.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * お知らせテーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class InfoTbl implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** info_id. */
	private Integer infoId;

	/** title. */
	private String title;

	/** msg. */
	private String msg;

	/** level. */
	private Integer level;

	/** info_date. */
	private Date infoDate;

	/** 未読テーブル 一覧. */
	private Set<UnreadTbl> unreadTblSet;

	/**
	 * コンストラクタ.
	 */
	public InfoTbl() {
		this.unreadTblSet = new HashSet<UnreadTbl>();
	}

	/**
	 * info_id を設定します.
	 * 
	 * @param infoId
	 *            info_id
	 */
	public void setInfoId(Integer infoId) {
		this.infoId = infoId;
	}

	/**
	 * info_id を取得します.
	 * 
	 * @return info_id
	 */
	public Integer getInfoId() {
		return this.infoId;
	}

	/**
	 * title を設定します.
	 * 
	 * @param title
	 *            title
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * title を取得します.
	 * 
	 * @return title
	 */
	public String getTitle() {
		return this.title;
	}

	/**
	 * msg を設定します.
	 * 
	 * @param msg
	 *            msg
	 */
	public void setMsg(String msg) {
		this.msg = msg;
	}

	/**
	 * msg を取得します.
	 * 
	 * @return msg
	 */
	public String getMsg() {
		return this.msg;
	}

	/**
	 * level を設定します.
	 * 
	 * @param level
	 *            level
	 */
	public void setLevel(Integer level) {
		this.level = level;
	}

	/**
	 * level を取得します.
	 * 
	 * @return level
	 */
	public Integer getLevel() {
		return this.level;
	}

	/**
	 * info_date を設定します.
	 * 
	 * @param infoDate
	 *            info_date
	 */
	public void setInfoDate(Date infoDate) {
		this.infoDate = infoDate;
	}

	/**
	 * info_date を取得します.
	 * 
	 * @return info_date
	 */
	public Date getInfoDate() {
		return this.infoDate;
	}

	/**
	 * 未読テーブル 一覧を設定します.
	 * 
	 * @param unreadTblSet
	 *            未読テーブル 一覧
	 */
	public void setUnreadTblSet(Set<UnreadTbl> unreadTblSet) {
		this.unreadTblSet = unreadTblSet;
	}

	/**
	 * 未読テーブル を追加します.
	 * 
	 * @param unreadTbl
	 *            未読テーブル
	 */
	public void addUnreadTbl(UnreadTbl unreadTbl) {
		this.unreadTblSet.add(unreadTbl);
	}

	/**
	 * 未読テーブル 一覧を取得します.
	 * 
	 * @return 未読テーブル 一覧
	 */
	public Set<UnreadTbl> getUnreadTblSet() {
		return this.unreadTblSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((infoId == null) ? 0 : infoId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		InfoTbl other = (InfoTbl) obj;
		if (infoId == null) {
			if (other.infoId != null) {
				return false;
			}
		} else if (!infoId.equals(other.infoId)) {
			return false;
		}
		return true;
	}

}
