package jp.ac.asojuku.jobhuntingsystem.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 就職活動状況マスタ モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class JobhuntingStatusTbl implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** jobhunting_status_id. */
	private Integer jobhuntingStatusId;

	/** name. */
	private String name;

	/** 学生テーブル 一覧. */
	private Set<StudentTbl> studentTblSet;

	/**
	 * コンストラクタ.
	 */
	public JobhuntingStatusTbl() {
		this.studentTblSet = new HashSet<StudentTbl>();
	}

	/**
	 * jobhunting_status_id を設定します.
	 * 
	 * @param jobhuntingStatusId
	 *            jobhunting_status_id
	 */
	public void setJobhuntingStatusId(Integer jobhuntingStatusId) {
		this.jobhuntingStatusId = jobhuntingStatusId;
	}

	/**
	 * jobhunting_status_id を取得します.
	 * 
	 * @return jobhunting_status_id
	 */
	public Integer getJobhuntingStatusId() {
		return this.jobhuntingStatusId;
	}

	/**
	 * name を設定します.
	 * 
	 * @param name
	 *            name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * name を取得します.
	 * 
	 * @return name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * 学生テーブル 一覧を設定します.
	 * 
	 * @param studentTblSet
	 *            学生テーブル 一覧
	 */
	public void setStudentTblSet(Set<StudentTbl> studentTblSet) {
		this.studentTblSet = studentTblSet;
	}

	/**
	 * 学生テーブル を追加します.
	 * 
	 * @param studentTbl
	 *            学生テーブル
	 */
	public void addStudentTbl(StudentTbl studentTbl) {
		this.studentTblSet.add(studentTbl);
	}

	/**
	 * 学生テーブル 一覧を取得します.
	 * 
	 * @return 学生テーブル 一覧
	 */
	public Set<StudentTbl> getStudentTblSet() {
		return this.studentTblSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((jobhuntingStatusId == null) ? 0 : jobhuntingStatusId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		JobhuntingStatusTbl other = (JobhuntingStatusTbl) obj;
		if (jobhuntingStatusId == null) {
			if (other.jobhuntingStatusId != null) {
				return false;
			}
		} else if (!jobhuntingStatusId.equals(other.jobhuntingStatusId)) {
			return false;
		}
		return true;
	}

}
