package jp.ac.asojuku.jobhuntingsystem.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 就職活動詳細テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class JobHuntingDetailTbl implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** job_hunting_detail_id. */
	private Integer jobHuntingDetailId;

	/** 就職テーブル. */
	private JobHuntingTbl jobHuntingTbl;

	/** stateus. */
	private Integer stateus;

	/** step_start_datetime. */
	private Date stepStartDatetime;

	/** イベントテーブル. */
	private EventTbl eventTbl;

	/** need_report. */
	private Integer needReport;

	/** 報告書 一覧. */
	private Set<ReportTbl> reportTblSet;

	/**
	 * コンストラクタ.
	 */
	public JobHuntingDetailTbl() {
		this.reportTblSet = new HashSet<ReportTbl>();
	}

	/**
	 * job_hunting_detail_id を設定します.
	 * 
	 * @param jobHuntingDetailId
	 *            job_hunting_detail_id
	 */
	public void setJobHuntingDetailId(Integer jobHuntingDetailId) {
		this.jobHuntingDetailId = jobHuntingDetailId;
	}

	/**
	 * job_hunting_detail_id を取得します.
	 * 
	 * @return job_hunting_detail_id
	 */
	public Integer getJobHuntingDetailId() {
		return this.jobHuntingDetailId;
	}

	/**
	 * 就職テーブル を設定します.
	 * 
	 * @param jobHuntingTbl
	 *            就職テーブル
	 */
	public void setJobHuntingTbl(JobHuntingTbl jobHuntingTbl) {
		this.jobHuntingTbl = jobHuntingTbl;
	}

	/**
	 * 就職テーブル を取得します.
	 * 
	 * @return 就職テーブル
	 */
	public JobHuntingTbl getJobHuntingTbl() {
		return this.jobHuntingTbl;
	}

	/**
	 * stateus を設定します.
	 * 
	 * @param stateus
	 *            stateus
	 */
	public void setStateus(Integer stateus) {
		this.stateus = stateus;
	}

	/**
	 * stateus を取得します.
	 * 
	 * @return stateus
	 */
	public Integer getStateus() {
		return this.stateus;
	}

	/**
	 * step_start_datetime を設定します.
	 * 
	 * @param stepStartDatetime
	 *            step_start_datetime
	 */
	public void setStepStartDatetime(Date stepStartDatetime) {
		this.stepStartDatetime = stepStartDatetime;
	}

	/**
	 * step_start_datetime を取得します.
	 * 
	 * @return step_start_datetime
	 */
	public Date getStepStartDatetime() {
		return this.stepStartDatetime;
	}

	/**
	 * イベントテーブル を設定します.
	 * 
	 * @param eventTbl
	 *            イベントテーブル
	 */
	public void setEventTbl(EventTbl eventTbl) {
		this.eventTbl = eventTbl;
	}

	/**
	 * イベントテーブル を取得します.
	 * 
	 * @return イベントテーブル
	 */
	public EventTbl getEventTbl() {
		return this.eventTbl;
	}

	/**
	 * need_report を設定します.
	 * 
	 * @param needReport
	 *            need_report
	 */
	public void setNeedReport(Integer needReport) {
		this.needReport = needReport;
	}

	/**
	 * need_report を取得します.
	 * 
	 * @return need_report
	 */
	public Integer getNeedReport() {
		return this.needReport;
	}

	/**
	 * 報告書 一覧を設定します.
	 * 
	 * @param reportTblSet
	 *            報告書 一覧
	 */
	public void setReportTblSet(Set<ReportTbl> reportTblSet) {
		this.reportTblSet = reportTblSet;
	}

	/**
	 * 報告書 を追加します.
	 * 
	 * @param reportTbl
	 *            報告書
	 */
	public void addReportTbl(ReportTbl reportTbl) {
		this.reportTblSet.add(reportTbl);
	}

	/**
	 * 報告書 一覧を取得します.
	 * 
	 * @return 報告書 一覧
	 */
	public Set<ReportTbl> getReportTblSet() {
		return this.reportTblSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((jobHuntingDetailId == null) ? 0 : jobHuntingDetailId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		JobHuntingDetailTbl other = (JobHuntingDetailTbl) obj;
		if (jobHuntingDetailId == null) {
			if (other.jobHuntingDetailId != null) {
				return false;
			}
		} else if (!jobHuntingDetailId.equals(other.jobHuntingDetailId)) {
			return false;
		}
		return true;
	}

}
