package jp.ac.asojuku.jobhuntingsystem.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * 個別メッセージテーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class MessageTbl implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** message_id. */
	private Integer messageId;

	/** msg. */
	private String msg;

	/** 学生テーブル. */
	private StudentTbl studentTbl;

	/** reg_date. */
	private Date regDate;

	/** level. */
	private Integer level;

	/**
	 * コンストラクタ.
	 */
	public MessageTbl() {
	}

	/**
	 * message_id を設定します.
	 * 
	 * @param messageId
	 *            message_id
	 */
	public void setMessageId(Integer messageId) {
		this.messageId = messageId;
	}

	/**
	 * message_id を取得します.
	 * 
	 * @return message_id
	 */
	public Integer getMessageId() {
		return this.messageId;
	}

	/**
	 * msg を設定します.
	 * 
	 * @param msg
	 *            msg
	 */
	public void setMsg(String msg) {
		this.msg = msg;
	}

	/**
	 * msg を取得します.
	 * 
	 * @return msg
	 */
	public String getMsg() {
		return this.msg;
	}

	/**
	 * 学生テーブル を設定します.
	 * 
	 * @param studentTbl
	 *            学生テーブル
	 */
	public void setStudentTbl(StudentTbl studentTbl) {
		this.studentTbl = studentTbl;
	}

	/**
	 * 学生テーブル を取得します.
	 * 
	 * @return 学生テーブル
	 */
	public StudentTbl getStudentTbl() {
		return this.studentTbl;
	}

	/**
	 * reg_date を設定します.
	 * 
	 * @param regDate
	 *            reg_date
	 */
	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	/**
	 * reg_date を取得します.
	 * 
	 * @return reg_date
	 */
	public Date getRegDate() {
		return this.regDate;
	}

	/**
	 * level を設定します.
	 * 
	 * @param level
	 *            level
	 */
	public void setLevel(Integer level) {
		this.level = level;
	}

	/**
	 * level を取得します.
	 * 
	 * @return level
	 */
	public Integer getLevel() {
		return this.level;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((messageId == null) ? 0 : messageId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		MessageTbl other = (MessageTbl) obj;
		if (messageId == null) {
			if (other.messageId != null) {
				return false;
			}
		} else if (!messageId.equals(other.messageId)) {
			return false;
		}
		return true;
	}

}
