package jp.ac.asojuku.jobhuntingsystem.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 採用求人テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RecruitmentTbl implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** recruitment_id. */
	private Integer recruitmentId;

	/** 企業テーブル. */
	private CompanyTbl companyTbl;

	/** type. */
	private Integer type;

	/** dormitory. */
	private Integer dormitory;

	/** salary_type. */
	private Integer salaryType;

	/** recrutiment_code. */
	private String recrutimentCode;

	/** 求人タイプテーブル. */
	private RecrutimentTypeTbl recrutimentTypeTbl;

	/** 業種テーブル. */
	private IndustrykindTbl industryKindId1industrykindTbl;

	/** 業種テーブル. */
	private IndustrykindTbl industryKindId2industrykindTbl;

	/** 業種テーブル. */
	private IndustrykindTbl industryKindId3industrykindTbl;

	/** 業種テーブル. */
	private IndustrykindTbl industryKindId4industrykindTbl;

	/** base_salary_for2. */
	private Integer baseSalaryFor2;

	/** base_salary_for3. */
	private Integer baseSalaryFor3;

	/** base_salary_for4. */
	private Integer baseSalaryFor4;

	/** salary_op1. */
	private String salaryOp1;

	/** salary_op2. */
	private String salaryOp2;

	/** salary_op3. */
	private String salaryOp3;

	/** salary_op1for2. */
	private Integer salaryOp1for2;

	/** salary_op1for3. */
	private Integer salaryOp1for3;

	/** salary_op1for4. */
	private Integer salaryOp1for4;

	/** salary_op2for2. */
	private Integer salaryOp2for2;

	/** salary_op2for3. */
	private Integer salaryOp2for3;

	/** salary_op2for4. */
	private Integer salaryOp2for4;

	/** salary_op3for2. */
	private Integer salaryOp3for2;

	/** salary_op3for3. */
	private Integer salaryOp3for3;

	/** salary_op3for4. */
	private Integer salaryOp3for4;

	/** required_resume. */
	private Integer requiredResume;

	/** required_expected. */
	private Integer requiredExpected;

	/** required_grades. */
	private Integer requiredGrades;

	/** required_else. */
	private String requiredElse;

	/** public_date. */
	private Date publicDate;

	/** target_year. */
	private Integer targetYear;

	/** offerstart_date. */
	private Date offerstartDate;

	/** offerend_flg. */
	private Integer offerendFlg;

	/** イベントテーブル 一覧. */
	private Set<EventTbl> eventTblSet;

	/**
	 * コンストラクタ.
	 */
	public RecruitmentTbl() {
		this.eventTblSet = new HashSet<EventTbl>();
	}

	/**
	 * recruitment_id を設定します.
	 * 
	 * @param recruitmentId
	 *            recruitment_id
	 */
	public void setRecruitmentId(Integer recruitmentId) {
		this.recruitmentId = recruitmentId;
	}

	/**
	 * recruitment_id を取得します.
	 * 
	 * @return recruitment_id
	 */
	public Integer getRecruitmentId() {
		return this.recruitmentId;
	}

	/**
	 * 企業テーブル を設定します.
	 * 
	 * @param companyTbl
	 *            企業テーブル
	 */
	public void setCompanyTbl(CompanyTbl companyTbl) {
		this.companyTbl = companyTbl;
	}

	/**
	 * 企業テーブル を取得します.
	 * 
	 * @return 企業テーブル
	 */
	public CompanyTbl getCompanyTbl() {
		return this.companyTbl;
	}

	/**
	 * type を設定します.
	 * 
	 * @param type
	 *            type
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * type を取得します.
	 * 
	 * @return type
	 */
	public Integer getType() {
		return this.type;
	}

	/**
	 * dormitory を設定します.
	 * 
	 * @param dormitory
	 *            dormitory
	 */
	public void setDormitory(Integer dormitory) {
		this.dormitory = dormitory;
	}

	/**
	 * dormitory を取得します.
	 * 
	 * @return dormitory
	 */
	public Integer getDormitory() {
		return this.dormitory;
	}

	/**
	 * salary_type を設定します.
	 * 
	 * @param salaryType
	 *            salary_type
	 */
	public void setSalaryType(Integer salaryType) {
		this.salaryType = salaryType;
	}

	/**
	 * salary_type を取得します.
	 * 
	 * @return salary_type
	 */
	public Integer getSalaryType() {
		return this.salaryType;
	}

	/**
	 * recrutiment_code を設定します.
	 * 
	 * @param recrutimentCode
	 *            recrutiment_code
	 */
	public void setRecrutimentCode(String recrutimentCode) {
		this.recrutimentCode = recrutimentCode;
	}

	/**
	 * recrutiment_code を取得します.
	 * 
	 * @return recrutiment_code
	 */
	public String getRecrutimentCode() {
		return this.recrutimentCode;
	}

	/**
	 * 求人タイプテーブル を設定します.
	 * 
	 * @param recrutimentTypeTbl
	 *            求人タイプテーブル
	 */
	public void setRecrutimentTypeTbl(RecrutimentTypeTbl recrutimentTypeTbl) {
		this.recrutimentTypeTbl = recrutimentTypeTbl;
	}

	/**
	 * 求人タイプテーブル を取得します.
	 * 
	 * @return 求人タイプテーブル
	 */
	public RecrutimentTypeTbl getRecrutimentTypeTbl() {
		return this.recrutimentTypeTbl;
	}

	/**
	 * 業種テーブル を設定します.
	 * 
	 * @param industryKindId1industrykindTbl
	 *            業種テーブル
	 */
	public void setIndustryKindId1industrykindTbl(IndustrykindTbl industryKindId1industrykindTbl) {
		this.industryKindId1industrykindTbl = industryKindId1industrykindTbl;
	}

	/**
	 * 業種テーブル を取得します.
	 * 
	 * @return 業種テーブル
	 */
	public IndustrykindTbl getIndustryKindId1industrykindTbl() {
		return this.industryKindId1industrykindTbl;
	}

	/**
	 * 業種テーブル を設定します.
	 * 
	 * @param industryKindId2industrykindTbl
	 *            業種テーブル
	 */
	public void setIndustryKindId2industrykindTbl(IndustrykindTbl industryKindId2industrykindTbl) {
		this.industryKindId2industrykindTbl = industryKindId2industrykindTbl;
	}

	/**
	 * 業種テーブル を取得します.
	 * 
	 * @return 業種テーブル
	 */
	public IndustrykindTbl getIndustryKindId2industrykindTbl() {
		return this.industryKindId2industrykindTbl;
	}

	/**
	 * 業種テーブル を設定します.
	 * 
	 * @param industryKindId3industrykindTbl
	 *            業種テーブル
	 */
	public void setIndustryKindId3industrykindTbl(IndustrykindTbl industryKindId3industrykindTbl) {
		this.industryKindId3industrykindTbl = industryKindId3industrykindTbl;
	}

	/**
	 * 業種テーブル を取得します.
	 * 
	 * @return 業種テーブル
	 */
	public IndustrykindTbl getIndustryKindId3industrykindTbl() {
		return this.industryKindId3industrykindTbl;
	}

	/**
	 * 業種テーブル を設定します.
	 * 
	 * @param industryKindId4industrykindTbl
	 *            業種テーブル
	 */
	public void setIndustryKindId4industrykindTbl(IndustrykindTbl industryKindId4industrykindTbl) {
		this.industryKindId4industrykindTbl = industryKindId4industrykindTbl;
	}

	/**
	 * 業種テーブル を取得します.
	 * 
	 * @return 業種テーブル
	 */
	public IndustrykindTbl getIndustryKindId4industrykindTbl() {
		return this.industryKindId4industrykindTbl;
	}

	/**
	 * base_salary_for2 を設定します.
	 * 
	 * @param baseSalaryFor2
	 *            base_salary_for2
	 */
	public void setBaseSalaryFor2(Integer baseSalaryFor2) {
		this.baseSalaryFor2 = baseSalaryFor2;
	}

	/**
	 * base_salary_for2 を取得します.
	 * 
	 * @return base_salary_for2
	 */
	public Integer getBaseSalaryFor2() {
		return this.baseSalaryFor2;
	}

	/**
	 * base_salary_for3 を設定します.
	 * 
	 * @param baseSalaryFor3
	 *            base_salary_for3
	 */
	public void setBaseSalaryFor3(Integer baseSalaryFor3) {
		this.baseSalaryFor3 = baseSalaryFor3;
	}

	/**
	 * base_salary_for3 を取得します.
	 * 
	 * @return base_salary_for3
	 */
	public Integer getBaseSalaryFor3() {
		return this.baseSalaryFor3;
	}

	/**
	 * base_salary_for4 を設定します.
	 * 
	 * @param baseSalaryFor4
	 *            base_salary_for4
	 */
	public void setBaseSalaryFor4(Integer baseSalaryFor4) {
		this.baseSalaryFor4 = baseSalaryFor4;
	}

	/**
	 * base_salary_for4 を取得します.
	 * 
	 * @return base_salary_for4
	 */
	public Integer getBaseSalaryFor4() {
		return this.baseSalaryFor4;
	}

	/**
	 * salary_op1 を設定します.
	 * 
	 * @param salaryOp1
	 *            salary_op1
	 */
	public void setSalaryOp1(String salaryOp1) {
		this.salaryOp1 = salaryOp1;
	}

	/**
	 * salary_op1 を取得します.
	 * 
	 * @return salary_op1
	 */
	public String getSalaryOp1() {
		return this.salaryOp1;
	}

	/**
	 * salary_op2 を設定します.
	 * 
	 * @param salaryOp2
	 *            salary_op2
	 */
	public void setSalaryOp2(String salaryOp2) {
		this.salaryOp2 = salaryOp2;
	}

	/**
	 * salary_op2 を取得します.
	 * 
	 * @return salary_op2
	 */
	public String getSalaryOp2() {
		return this.salaryOp2;
	}

	/**
	 * salary_op3 を設定します.
	 * 
	 * @param salaryOp3
	 *            salary_op3
	 */
	public void setSalaryOp3(String salaryOp3) {
		this.salaryOp3 = salaryOp3;
	}

	/**
	 * salary_op3 を取得します.
	 * 
	 * @return salary_op3
	 */
	public String getSalaryOp3() {
		return this.salaryOp3;
	}

	/**
	 * salary_op1for2 を設定します.
	 * 
	 * @param salaryOp1for2
	 *            salary_op1for2
	 */
	public void setSalaryOp1for2(Integer salaryOp1for2) {
		this.salaryOp1for2 = salaryOp1for2;
	}

	/**
	 * salary_op1for2 を取得します.
	 * 
	 * @return salary_op1for2
	 */
	public Integer getSalaryOp1for2() {
		return this.salaryOp1for2;
	}

	/**
	 * salary_op1for3 を設定します.
	 * 
	 * @param salaryOp1for3
	 *            salary_op1for3
	 */
	public void setSalaryOp1for3(Integer salaryOp1for3) {
		this.salaryOp1for3 = salaryOp1for3;
	}

	/**
	 * salary_op1for3 を取得します.
	 * 
	 * @return salary_op1for3
	 */
	public Integer getSalaryOp1for3() {
		return this.salaryOp1for3;
	}

	/**
	 * salary_op1for4 を設定します.
	 * 
	 * @param salaryOp1for4
	 *            salary_op1for4
	 */
	public void setSalaryOp1for4(Integer salaryOp1for4) {
		this.salaryOp1for4 = salaryOp1for4;
	}

	/**
	 * salary_op1for4 を取得します.
	 * 
	 * @return salary_op1for4
	 */
	public Integer getSalaryOp1for4() {
		return this.salaryOp1for4;
	}

	/**
	 * salary_op2for2 を設定します.
	 * 
	 * @param salaryOp2for2
	 *            salary_op2for2
	 */
	public void setSalaryOp2for2(Integer salaryOp2for2) {
		this.salaryOp2for2 = salaryOp2for2;
	}

	/**
	 * salary_op2for2 を取得します.
	 * 
	 * @return salary_op2for2
	 */
	public Integer getSalaryOp2for2() {
		return this.salaryOp2for2;
	}

	/**
	 * salary_op2for3 を設定します.
	 * 
	 * @param salaryOp2for3
	 *            salary_op2for3
	 */
	public void setSalaryOp2for3(Integer salaryOp2for3) {
		this.salaryOp2for3 = salaryOp2for3;
	}

	/**
	 * salary_op2for3 を取得します.
	 * 
	 * @return salary_op2for3
	 */
	public Integer getSalaryOp2for3() {
		return this.salaryOp2for3;
	}

	/**
	 * salary_op2for4 を設定します.
	 * 
	 * @param salaryOp2for4
	 *            salary_op2for4
	 */
	public void setSalaryOp2for4(Integer salaryOp2for4) {
		this.salaryOp2for4 = salaryOp2for4;
	}

	/**
	 * salary_op2for4 を取得します.
	 * 
	 * @return salary_op2for4
	 */
	public Integer getSalaryOp2for4() {
		return this.salaryOp2for4;
	}

	/**
	 * salary_op3for2 を設定します.
	 * 
	 * @param salaryOp3for2
	 *            salary_op3for2
	 */
	public void setSalaryOp3for2(Integer salaryOp3for2) {
		this.salaryOp3for2 = salaryOp3for2;
	}

	/**
	 * salary_op3for2 を取得します.
	 * 
	 * @return salary_op3for2
	 */
	public Integer getSalaryOp3for2() {
		return this.salaryOp3for2;
	}

	/**
	 * salary_op3for3 を設定します.
	 * 
	 * @param salaryOp3for3
	 *            salary_op3for3
	 */
	public void setSalaryOp3for3(Integer salaryOp3for3) {
		this.salaryOp3for3 = salaryOp3for3;
	}

	/**
	 * salary_op3for3 を取得します.
	 * 
	 * @return salary_op3for3
	 */
	public Integer getSalaryOp3for3() {
		return this.salaryOp3for3;
	}

	/**
	 * salary_op3for4 を設定します.
	 * 
	 * @param salaryOp3for4
	 *            salary_op3for4
	 */
	public void setSalaryOp3for4(Integer salaryOp3for4) {
		this.salaryOp3for4 = salaryOp3for4;
	}

	/**
	 * salary_op3for4 を取得します.
	 * 
	 * @return salary_op3for4
	 */
	public Integer getSalaryOp3for4() {
		return this.salaryOp3for4;
	}

	/**
	 * required_resume を設定します.
	 * 
	 * @param requiredResume
	 *            required_resume
	 */
	public void setRequiredResume(Integer requiredResume) {
		this.requiredResume = requiredResume;
	}

	/**
	 * required_resume を取得します.
	 * 
	 * @return required_resume
	 */
	public Integer getRequiredResume() {
		return this.requiredResume;
	}

	/**
	 * required_expected を設定します.
	 * 
	 * @param requiredExpected
	 *            required_expected
	 */
	public void setRequiredExpected(Integer requiredExpected) {
		this.requiredExpected = requiredExpected;
	}

	/**
	 * required_expected を取得します.
	 * 
	 * @return required_expected
	 */
	public Integer getRequiredExpected() {
		return this.requiredExpected;
	}

	/**
	 * required_grades を設定します.
	 * 
	 * @param requiredGrades
	 *            required_grades
	 */
	public void setRequiredGrades(Integer requiredGrades) {
		this.requiredGrades = requiredGrades;
	}

	/**
	 * required_grades を取得します.
	 * 
	 * @return required_grades
	 */
	public Integer getRequiredGrades() {
		return this.requiredGrades;
	}

	/**
	 * required_else を設定します.
	 * 
	 * @param requiredElse
	 *            required_else
	 */
	public void setRequiredElse(String requiredElse) {
		this.requiredElse = requiredElse;
	}

	/**
	 * required_else を取得します.
	 * 
	 * @return required_else
	 */
	public String getRequiredElse() {
		return this.requiredElse;
	}

	/**
	 * public_date を設定します.
	 * 
	 * @param publicDate
	 *            public_date
	 */
	public void setPublicDate(Date publicDate) {
		this.publicDate = publicDate;
	}

	/**
	 * public_date を取得します.
	 * 
	 * @return public_date
	 */
	public Date getPublicDate() {
		return this.publicDate;
	}

	/**
	 * target_year を設定します.
	 * 
	 * @param targetYear
	 *            target_year
	 */
	public void setTargetYear(Integer targetYear) {
		this.targetYear = targetYear;
	}

	/**
	 * target_year を取得します.
	 * 
	 * @return target_year
	 */
	public Integer getTargetYear() {
		return this.targetYear;
	}

	/**
	 * offerstart_date を設定します.
	 * 
	 * @param offerstartDate
	 *            offerstart_date
	 */
	public void setOfferstartDate(Date offerstartDate) {
		this.offerstartDate = offerstartDate;
	}

	/**
	 * offerstart_date を取得します.
	 * 
	 * @return offerstart_date
	 */
	public Date getOfferstartDate() {
		return this.offerstartDate;
	}

	/**
	 * offerend_flg を設定します.
	 * 
	 * @param offerendFlg
	 *            offerend_flg
	 */
	public void setOfferendFlg(Integer offerendFlg) {
		this.offerendFlg = offerendFlg;
	}

	/**
	 * offerend_flg を取得します.
	 * 
	 * @return offerend_flg
	 */
	public Integer getOfferendFlg() {
		return this.offerendFlg;
	}

	/**
	 * イベントテーブル 一覧を設定します.
	 * 
	 * @param eventTblSet
	 *            イベントテーブル 一覧
	 */
	public void setEventTblSet(Set<EventTbl> eventTblSet) {
		this.eventTblSet = eventTblSet;
	}

	/**
	 * イベントテーブル を追加します.
	 * 
	 * @param eventTbl
	 *            イベントテーブル
	 */
	public void addEventTbl(EventTbl eventTbl) {
		this.eventTblSet.add(eventTbl);
	}

	/**
	 * イベントテーブル 一覧を取得します.
	 * 
	 * @return イベントテーブル 一覧
	 */
	public Set<EventTbl> getEventTblSet() {
		return this.eventTblSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((recruitmentId == null) ? 0 : recruitmentId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		RecruitmentTbl other = (RecruitmentTbl) obj;
		if (recruitmentId == null) {
			if (other.recruitmentId != null) {
				return false;
			}
		} else if (!recruitmentId.equals(other.recruitmentId)) {
			return false;
		}
		return true;
	}

}
