package jp.ac.asojuku.jobhuntingsystem.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 求人タイプテーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RecrutimentTypeTbl implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** recrutiment_type_id. */
	private Integer recrutimentTypeId;

	/** name. */
	private String name;

	/** 採用求人テーブル 一覧. */
	private Set<RecruitmentTbl> recruitmentTblSet;

	/**
	 * コンストラクタ.
	 */
	public RecrutimentTypeTbl() {
		this.recruitmentTblSet = new HashSet<RecruitmentTbl>();
	}

	/**
	 * recrutiment_type_id を設定します.
	 * 
	 * @param recrutimentTypeId
	 *            recrutiment_type_id
	 */
	public void setRecrutimentTypeId(Integer recrutimentTypeId) {
		this.recrutimentTypeId = recrutimentTypeId;
	}

	/**
	 * recrutiment_type_id を取得します.
	 * 
	 * @return recrutiment_type_id
	 */
	public Integer getRecrutimentTypeId() {
		return this.recrutimentTypeId;
	}

	/**
	 * name を設定します.
	 * 
	 * @param name
	 *            name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * name を取得します.
	 * 
	 * @return name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * 採用求人テーブル 一覧を設定します.
	 * 
	 * @param recruitmentTblSet
	 *            採用求人テーブル 一覧
	 */
	public void setRecruitmentTblSet(Set<RecruitmentTbl> recruitmentTblSet) {
		this.recruitmentTblSet = recruitmentTblSet;
	}

	/**
	 * 採用求人テーブル を追加します.
	 * 
	 * @param recruitmentTbl
	 *            採用求人テーブル
	 */
	public void addRecruitmentTbl(RecruitmentTbl recruitmentTbl) {
		this.recruitmentTblSet.add(recruitmentTbl);
	}

	/**
	 * 採用求人テーブル 一覧を取得します.
	 * 
	 * @return 採用求人テーブル 一覧
	 */
	public Set<RecruitmentTbl> getRecruitmentTblSet() {
		return this.recruitmentTblSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((recrutimentTypeId == null) ? 0 : recrutimentTypeId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		RecrutimentTypeTbl other = (RecrutimentTypeTbl) obj;
		if (recrutimentTypeId == null) {
			if (other.recrutimentTypeId != null) {
				return false;
			}
		} else if (!recrutimentTypeId.equals(other.recrutimentTypeId)) {
			return false;
		}
		return true;
	}

}
