package jp.ac.asojuku.jobhuntingsystem.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 役割テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RoleTbl implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** role_id. */
	private Integer roleId;

	/** name. */
	private String name;

	/** 管理者テーブル 一覧. */
	private Set<AdminTbl> adminTblSet;

	/**
	 * コンストラクタ.
	 */
	public RoleTbl() {
		this.adminTblSet = new HashSet<AdminTbl>();
	}

	/**
	 * role_id を設定します.
	 * 
	 * @param roleId
	 *            role_id
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * role_id を取得します.
	 * 
	 * @return role_id
	 */
	public Integer getRoleId() {
		return this.roleId;
	}

	/**
	 * name を設定します.
	 * 
	 * @param name
	 *            name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * name を取得します.
	 * 
	 * @return name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * 管理者テーブル 一覧を設定します.
	 * 
	 * @param adminTblSet
	 *            管理者テーブル 一覧
	 */
	public void setAdminTblSet(Set<AdminTbl> adminTblSet) {
		this.adminTblSet = adminTblSet;
	}

	/**
	 * 管理者テーブル を追加します.
	 * 
	 * @param adminTbl
	 *            管理者テーブル
	 */
	public void addAdminTbl(AdminTbl adminTbl) {
		this.adminTblSet.add(adminTbl);
	}

	/**
	 * 管理者テーブル 一覧を取得します.
	 * 
	 * @return 管理者テーブル 一覧
	 */
	public Set<AdminTbl> getAdminTblSet() {
		return this.adminTblSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((roleId == null) ? 0 : roleId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		RoleTbl other = (RoleTbl) obj;
		if (roleId == null) {
			if (other.roleId != null) {
				return false;
			}
		} else if (!roleId.equals(other.roleId)) {
			return false;
		}
		return true;
	}

}
