package jp.ac.asojuku.jobhuntingsystem.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * ステップテーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class StepTbl implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** step_id. */
	private Integer stepId;

	/** name. */
	private String name;

	/** イベントテーブル 一覧. */
	private Set<EventTbl> eventTblSet;

	/**
	 * コンストラクタ.
	 */
	public StepTbl() {
		this.eventTblSet = new HashSet<EventTbl>();
	}

	/**
	 * step_id を設定します.
	 * 
	 * @param stepId
	 *            step_id
	 */
	public void setStepId(Integer stepId) {
		this.stepId = stepId;
	}

	/**
	 * step_id を取得します.
	 * 
	 * @return step_id
	 */
	public Integer getStepId() {
		return this.stepId;
	}

	/**
	 * name を設定します.
	 * 
	 * @param name
	 *            name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * name を取得します.
	 * 
	 * @return name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * イベントテーブル 一覧を設定します.
	 * 
	 * @param eventTblSet
	 *            イベントテーブル 一覧
	 */
	public void setEventTblSet(Set<EventTbl> eventTblSet) {
		this.eventTblSet = eventTblSet;
	}

	/**
	 * イベントテーブル を追加します.
	 * 
	 * @param eventTbl
	 *            イベントテーブル
	 */
	public void addEventTbl(EventTbl eventTbl) {
		this.eventTblSet.add(eventTbl);
	}

	/**
	 * イベントテーブル 一覧を取得します.
	 * 
	 * @return イベントテーブル 一覧
	 */
	public Set<EventTbl> getEventTblSet() {
		return this.eventTblSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((stepId == null) ? 0 : stepId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		StepTbl other = (StepTbl) obj;
		if (stepId == null) {
			if (other.stepId != null) {
				return false;
			}
		} else if (!stepId.equals(other.stepId)) {
			return false;
		}
		return true;
	}

}
