package jp.ac.asojuku.jobhuntingsystem.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 学生テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class StudentTbl implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** student_id. */
	private Integer studentId;

	/** password. */
	private String password;

	/** student_no. */
	private String studentNo;

	/** name. */
	private String name;

	/** mail. */
	private String mail;

	/** 学科テーブル. */
	private ClassTbl classTbl;

	/** 就職活動状況マスタ. */
	private JobhuntingStatusTbl jobhuntingStatusTbl;

	/** image. */
	private String image;

	/** tel. */
	private String tel;

	/** address. */
	private String address;

	/** year. */
	private Integer year;

	/** c_trust. */
	private Integer cTrust;

	/** c_entrapment. */
	private Integer cEntrapment;

	/** c_objectivity. */
	private Integer cObjectivity;

	/** c_physicality. */
	private Integer cPhysicality;

	/** c_moodiness. */
	private Integer cMoodiness;

	/** c_persistence. */
	private Integer cPersistence;

	/** c_regularity. */
	private Integer cRegularity;

	/** c_competitiveness. */
	private Integer cCompetitiveness;

	/** c_selfesteem. */
	private Integer cSelfesteem;

	/** c_prudence. */
	private Integer cPrudence;

	/** c_bearishness. */
	private Integer cBearishness;

	/** c_surroundings. */
	private Integer cSurroundings;

	/** c_science. */
	private Integer cScience;

	/** c_society. */
	private Integer cSociety;

	/** c_psychology. */
	private Integer cPsychology;

	/** c_art. */
	private Integer cArt;

	/** c_positivity. */
	private Integer cPositivity;

	/** c_cooperativeness. */
	private Integer cCooperativeness;

	/** c_responsibility. */
	private Integer cResponsibility;

	/** c_reliability. */
	private Integer cReliability;

	/** c_leadership. */
	private Integer cLeadership;

	/** c_empathy. */
	private Integer cEmpathy;

	/** c_emotional_stability. */
	private Integer cEmotionalStability;

	/** c_obedience. */
	private Integer cObedience;

	/** c_autonomy. */
	private Integer cAutonomy;

	/** c_moratorium. */
	private Integer cMoratorium;

	/** c_desire_success. */
	private Integer cDesireSuccess;

	/** c_affinity. */
	private Integer cAffinity;

	/** c_seeking. */
	private Integer cSeeking;

	/** c_manifestation. */
	private Integer cManifestation;

	/** c_order. */
	private Integer cOrder;

	/** c_material. */
	private Integer cMaterial;

	/** c_crisis_resistance. */
	private Integer cCrisisResistance;

	/** c_independence. */
	private Integer cIndependence;

	/** c_control. */
	private Integer cControl;

	/** c_workethic. */
	private Integer cWorkethic;

	/** c_active. */
	private Integer cActive;

	/** c_enthusiasm. */
	private Integer cEnthusiasm;

	/** c_perseverance. */
	private Integer cPerseverance;

	/** c_responsibility2. */
	private Integer cResponsibility2;

	/** c_decisive. */
	private Integer cDecisive;

	/** c_leadership2. */
	private Integer cLeadership2;

	/** c_leader. */
	private Integer cLeader;

	/** c_selftrust. */
	private Integer cSelftrust;

	/** c_adjustment. */
	private Integer cAdjustment;

	/** c_negotiation. */
	private Integer cNegotiation;

	/** c_innovative. */
	private Integer cInnovative;

	/** c_analysis. */
	private Integer cAnalysis;

	/** c_Insight. */
	private Integer cInsight;

	/** c_planning. */
	private Integer cPlanning;

	/** c_expertise. */
	private Integer cExpertise;

	/** c_utilization. */
	private Integer cUtilization;

	/** c_general. */
	private Integer cGeneral;

	/** c_mental. */
	private Integer cMental;

	/** c_legwaist. */
	private Integer cLegwaist;

	/** c_concentration. */
	private Integer cConcentration;

	/** c_standardization. */
	private Integer cStandardization;

	/** c_range. */
	private Integer cRange;

	/** c_established. */
	private Integer cEstablished;

	/** c_typejudge. */
	private String cTypejudge;

	/** 進路決定テーブル 一覧. */
	private Set<CareerReportTbl> careerReportTblSet;

	/** 就職テーブル 一覧. */
	private Set<JobHuntingTbl> jobHuntingTblSet;

	/** 個別メッセージテーブル 一覧. */
	private Set<MessageTbl> messageTblSet;

	/** 未読テーブル 一覧. */
	private Set<UnreadTbl> unreadTblSet;

	/**
	 * コンストラクタ.
	 */
	public StudentTbl() {
		this.careerReportTblSet = new HashSet<CareerReportTbl>();
		this.jobHuntingTblSet = new HashSet<JobHuntingTbl>();
		this.messageTblSet = new HashSet<MessageTbl>();
		this.unreadTblSet = new HashSet<UnreadTbl>();
	}

	/**
	 * student_id を設定します.
	 * 
	 * @param studentId
	 *            student_id
	 */
	public void setStudentId(Integer studentId) {
		this.studentId = studentId;
	}

	/**
	 * student_id を取得します.
	 * 
	 * @return student_id
	 */
	public Integer getStudentId() {
		return this.studentId;
	}

	/**
	 * password を設定します.
	 * 
	 * @param password
	 *            password
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * password を取得します.
	 * 
	 * @return password
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * student_no を設定します.
	 * 
	 * @param studentNo
	 *            student_no
	 */
	public void setStudentNo(String studentNo) {
		this.studentNo = studentNo;
	}

	/**
	 * student_no を取得します.
	 * 
	 * @return student_no
	 */
	public String getStudentNo() {
		return this.studentNo;
	}

	/**
	 * name を設定します.
	 * 
	 * @param name
	 *            name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * name を取得します.
	 * 
	 * @return name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * mail を設定します.
	 * 
	 * @param mail
	 *            mail
	 */
	public void setMail(String mail) {
		this.mail = mail;
	}

	/**
	 * mail を取得します.
	 * 
	 * @return mail
	 */
	public String getMail() {
		return this.mail;
	}

	/**
	 * 学科テーブル を設定します.
	 * 
	 * @param classTbl
	 *            学科テーブル
	 */
	public void setClassTbl(ClassTbl classTbl) {
		this.classTbl = classTbl;
	}

	/**
	 * 学科テーブル を取得します.
	 * 
	 * @return 学科テーブル
	 */
	public ClassTbl getClassTbl() {
		return this.classTbl;
	}

	/**
	 * 就職活動状況マスタ を設定します.
	 * 
	 * @param jobhuntingStatusTbl
	 *            就職活動状況マスタ
	 */
	public void setJobhuntingStatusTbl(JobhuntingStatusTbl jobhuntingStatusTbl) {
		this.jobhuntingStatusTbl = jobhuntingStatusTbl;
	}

	/**
	 * 就職活動状況マスタ を取得します.
	 * 
	 * @return 就職活動状況マスタ
	 */
	public JobhuntingStatusTbl getJobhuntingStatusTbl() {
		return this.jobhuntingStatusTbl;
	}

	/**
	 * image を設定します.
	 * 
	 * @param image
	 *            image
	 */
	public void setImage(String image) {
		this.image = image;
	}

	/**
	 * image を取得します.
	 * 
	 * @return image
	 */
	public String getImage() {
		return this.image;
	}

	/**
	 * tel を設定します.
	 * 
	 * @param tel
	 *            tel
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * tel を取得します.
	 * 
	 * @return tel
	 */
	public String getTel() {
		return this.tel;
	}

	/**
	 * address を設定します.
	 * 
	 * @param address
	 *            address
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * address を取得します.
	 * 
	 * @return address
	 */
	public String getAddress() {
		return this.address;
	}

	/**
	 * year を設定します.
	 * 
	 * @param year
	 *            year
	 */
	public void setYear(Integer year) {
		this.year = year;
	}

	/**
	 * year を取得します.
	 * 
	 * @return year
	 */
	public Integer getYear() {
		return this.year;
	}

	/**
	 * c_trust を設定します.
	 * 
	 * @param cTrust
	 *            c_trust
	 */
	public void setCTrust(Integer cTrust) {
		this.cTrust = cTrust;
	}

	/**
	 * c_trust を取得します.
	 * 
	 * @return c_trust
	 */
	public Integer getCTrust() {
		return this.cTrust;
	}

	/**
	 * c_entrapment を設定します.
	 * 
	 * @param cEntrapment
	 *            c_entrapment
	 */
	public void setCEntrapment(Integer cEntrapment) {
		this.cEntrapment = cEntrapment;
	}

	/**
	 * c_entrapment を取得します.
	 * 
	 * @return c_entrapment
	 */
	public Integer getCEntrapment() {
		return this.cEntrapment;
	}

	/**
	 * c_objectivity を設定します.
	 * 
	 * @param cObjectivity
	 *            c_objectivity
	 */
	public void setCObjectivity(Integer cObjectivity) {
		this.cObjectivity = cObjectivity;
	}

	/**
	 * c_objectivity を取得します.
	 * 
	 * @return c_objectivity
	 */
	public Integer getCObjectivity() {
		return this.cObjectivity;
	}

	/**
	 * c_physicality を設定します.
	 * 
	 * @param cPhysicality
	 *            c_physicality
	 */
	public void setCPhysicality(Integer cPhysicality) {
		this.cPhysicality = cPhysicality;
	}

	/**
	 * c_physicality を取得します.
	 * 
	 * @return c_physicality
	 */
	public Integer getCPhysicality() {
		return this.cPhysicality;
	}

	/**
	 * c_moodiness を設定します.
	 * 
	 * @param cMoodiness
	 *            c_moodiness
	 */
	public void setCMoodiness(Integer cMoodiness) {
		this.cMoodiness = cMoodiness;
	}

	/**
	 * c_moodiness を取得します.
	 * 
	 * @return c_moodiness
	 */
	public Integer getCMoodiness() {
		return this.cMoodiness;
	}

	/**
	 * c_persistence を設定します.
	 * 
	 * @param cPersistence
	 *            c_persistence
	 */
	public void setCPersistence(Integer cPersistence) {
		this.cPersistence = cPersistence;
	}

	/**
	 * c_persistence を取得します.
	 * 
	 * @return c_persistence
	 */
	public Integer getCPersistence() {
		return this.cPersistence;
	}

	/**
	 * c_regularity を設定します.
	 * 
	 * @param cRegularity
	 *            c_regularity
	 */
	public void setCRegularity(Integer cRegularity) {
		this.cRegularity = cRegularity;
	}

	/**
	 * c_regularity を取得します.
	 * 
	 * @return c_regularity
	 */
	public Integer getCRegularity() {
		return this.cRegularity;
	}

	/**
	 * c_competitiveness を設定します.
	 * 
	 * @param cCompetitiveness
	 *            c_competitiveness
	 */
	public void setCCompetitiveness(Integer cCompetitiveness) {
		this.cCompetitiveness = cCompetitiveness;
	}

	/**
	 * c_competitiveness を取得します.
	 * 
	 * @return c_competitiveness
	 */
	public Integer getCCompetitiveness() {
		return this.cCompetitiveness;
	}

	/**
	 * c_selfesteem を設定します.
	 * 
	 * @param cSelfesteem
	 *            c_selfesteem
	 */
	public void setCSelfesteem(Integer cSelfesteem) {
		this.cSelfesteem = cSelfesteem;
	}

	/**
	 * c_selfesteem を取得します.
	 * 
	 * @return c_selfesteem
	 */
	public Integer getCSelfesteem() {
		return this.cSelfesteem;
	}

	/**
	 * c_prudence を設定します.
	 * 
	 * @param cPrudence
	 *            c_prudence
	 */
	public void setCPrudence(Integer cPrudence) {
		this.cPrudence = cPrudence;
	}

	/**
	 * c_prudence を取得します.
	 * 
	 * @return c_prudence
	 */
	public Integer getCPrudence() {
		return this.cPrudence;
	}

	/**
	 * c_bearishness を設定します.
	 * 
	 * @param cBearishness
	 *            c_bearishness
	 */
	public void setCBearishness(Integer cBearishness) {
		this.cBearishness = cBearishness;
	}

	/**
	 * c_bearishness を取得します.
	 * 
	 * @return c_bearishness
	 */
	public Integer getCBearishness() {
		return this.cBearishness;
	}

	/**
	 * c_surroundings を設定します.
	 * 
	 * @param cSurroundings
	 *            c_surroundings
	 */
	public void setCSurroundings(Integer cSurroundings) {
		this.cSurroundings = cSurroundings;
	}

	/**
	 * c_surroundings を取得します.
	 * 
	 * @return c_surroundings
	 */
	public Integer getCSurroundings() {
		return this.cSurroundings;
	}

	/**
	 * c_science を設定します.
	 * 
	 * @param cScience
	 *            c_science
	 */
	public void setCScience(Integer cScience) {
		this.cScience = cScience;
	}

	/**
	 * c_science を取得します.
	 * 
	 * @return c_science
	 */
	public Integer getCScience() {
		return this.cScience;
	}

	/**
	 * c_society を設定します.
	 * 
	 * @param cSociety
	 *            c_society
	 */
	public void setCSociety(Integer cSociety) {
		this.cSociety = cSociety;
	}

	/**
	 * c_society を取得します.
	 * 
	 * @return c_society
	 */
	public Integer getCSociety() {
		return this.cSociety;
	}

	/**
	 * c_psychology を設定します.
	 * 
	 * @param cPsychology
	 *            c_psychology
	 */
	public void setCPsychology(Integer cPsychology) {
		this.cPsychology = cPsychology;
	}

	/**
	 * c_psychology を取得します.
	 * 
	 * @return c_psychology
	 */
	public Integer getCPsychology() {
		return this.cPsychology;
	}

	/**
	 * c_art を設定します.
	 * 
	 * @param cArt
	 *            c_art
	 */
	public void setCArt(Integer cArt) {
		this.cArt = cArt;
	}

	/**
	 * c_art を取得します.
	 * 
	 * @return c_art
	 */
	public Integer getCArt() {
		return this.cArt;
	}

	/**
	 * c_positivity を設定します.
	 * 
	 * @param cPositivity
	 *            c_positivity
	 */
	public void setCPositivity(Integer cPositivity) {
		this.cPositivity = cPositivity;
	}

	/**
	 * c_positivity を取得します.
	 * 
	 * @return c_positivity
	 */
	public Integer getCPositivity() {
		return this.cPositivity;
	}

	/**
	 * c_cooperativeness を設定します.
	 * 
	 * @param cCooperativeness
	 *            c_cooperativeness
	 */
	public void setCCooperativeness(Integer cCooperativeness) {
		this.cCooperativeness = cCooperativeness;
	}

	/**
	 * c_cooperativeness を取得します.
	 * 
	 * @return c_cooperativeness
	 */
	public Integer getCCooperativeness() {
		return this.cCooperativeness;
	}

	/**
	 * c_responsibility を設定します.
	 * 
	 * @param cResponsibility
	 *            c_responsibility
	 */
	public void setCResponsibility(Integer cResponsibility) {
		this.cResponsibility = cResponsibility;
	}

	/**
	 * c_responsibility を取得します.
	 * 
	 * @return c_responsibility
	 */
	public Integer getCResponsibility() {
		return this.cResponsibility;
	}

	/**
	 * c_reliability を設定します.
	 * 
	 * @param cReliability
	 *            c_reliability
	 */
	public void setCReliability(Integer cReliability) {
		this.cReliability = cReliability;
	}

	/**
	 * c_reliability を取得します.
	 * 
	 * @return c_reliability
	 */
	public Integer getCReliability() {
		return this.cReliability;
	}

	/**
	 * c_leadership を設定します.
	 * 
	 * @param cLeadership
	 *            c_leadership
	 */
	public void setCLeadership(Integer cLeadership) {
		this.cLeadership = cLeadership;
	}

	/**
	 * c_leadership を取得します.
	 * 
	 * @return c_leadership
	 */
	public Integer getCLeadership() {
		return this.cLeadership;
	}

	/**
	 * c_empathy を設定します.
	 * 
	 * @param cEmpathy
	 *            c_empathy
	 */
	public void setCEmpathy(Integer cEmpathy) {
		this.cEmpathy = cEmpathy;
	}

	/**
	 * c_empathy を取得します.
	 * 
	 * @return c_empathy
	 */
	public Integer getCEmpathy() {
		return this.cEmpathy;
	}

	/**
	 * c_emotional_stability を設定します.
	 * 
	 * @param cEmotionalStability
	 *            c_emotional_stability
	 */
	public void setCEmotionalStability(Integer cEmotionalStability) {
		this.cEmotionalStability = cEmotionalStability;
	}

	/**
	 * c_emotional_stability を取得します.
	 * 
	 * @return c_emotional_stability
	 */
	public Integer getCEmotionalStability() {
		return this.cEmotionalStability;
	}

	/**
	 * c_obedience を設定します.
	 * 
	 * @param cObedience
	 *            c_obedience
	 */
	public void setCObedience(Integer cObedience) {
		this.cObedience = cObedience;
	}

	/**
	 * c_obedience を取得します.
	 * 
	 * @return c_obedience
	 */
	public Integer getCObedience() {
		return this.cObedience;
	}

	/**
	 * c_autonomy を設定します.
	 * 
	 * @param cAutonomy
	 *            c_autonomy
	 */
	public void setCAutonomy(Integer cAutonomy) {
		this.cAutonomy = cAutonomy;
	}

	/**
	 * c_autonomy を取得します.
	 * 
	 * @return c_autonomy
	 */
	public Integer getCAutonomy() {
		return this.cAutonomy;
	}

	/**
	 * c_moratorium を設定します.
	 * 
	 * @param cMoratorium
	 *            c_moratorium
	 */
	public void setCMoratorium(Integer cMoratorium) {
		this.cMoratorium = cMoratorium;
	}

	/**
	 * c_moratorium を取得します.
	 * 
	 * @return c_moratorium
	 */
	public Integer getCMoratorium() {
		return this.cMoratorium;
	}

	/**
	 * c_desire_success を設定します.
	 * 
	 * @param cDesireSuccess
	 *            c_desire_success
	 */
	public void setCDesireSuccess(Integer cDesireSuccess) {
		this.cDesireSuccess = cDesireSuccess;
	}

	/**
	 * c_desire_success を取得します.
	 * 
	 * @return c_desire_success
	 */
	public Integer getCDesireSuccess() {
		return this.cDesireSuccess;
	}

	/**
	 * c_affinity を設定します.
	 * 
	 * @param cAffinity
	 *            c_affinity
	 */
	public void setCAffinity(Integer cAffinity) {
		this.cAffinity = cAffinity;
	}

	/**
	 * c_affinity を取得します.
	 * 
	 * @return c_affinity
	 */
	public Integer getCAffinity() {
		return this.cAffinity;
	}

	/**
	 * c_seeking を設定します.
	 * 
	 * @param cSeeking
	 *            c_seeking
	 */
	public void setCSeeking(Integer cSeeking) {
		this.cSeeking = cSeeking;
	}

	/**
	 * c_seeking を取得します.
	 * 
	 * @return c_seeking
	 */
	public Integer getCSeeking() {
		return this.cSeeking;
	}

	/**
	 * c_manifestation を設定します.
	 * 
	 * @param cManifestation
	 *            c_manifestation
	 */
	public void setCManifestation(Integer cManifestation) {
		this.cManifestation = cManifestation;
	}

	/**
	 * c_manifestation を取得します.
	 * 
	 * @return c_manifestation
	 */
	public Integer getCManifestation() {
		return this.cManifestation;
	}

	/**
	 * c_order を設定します.
	 * 
	 * @param cOrder
	 *            c_order
	 */
	public void setCOrder(Integer cOrder) {
		this.cOrder = cOrder;
	}

	/**
	 * c_order を取得します.
	 * 
	 * @return c_order
	 */
	public Integer getCOrder() {
		return this.cOrder;
	}

	/**
	 * c_material を設定します.
	 * 
	 * @param cMaterial
	 *            c_material
	 */
	public void setCMaterial(Integer cMaterial) {
		this.cMaterial = cMaterial;
	}

	/**
	 * c_material を取得します.
	 * 
	 * @return c_material
	 */
	public Integer getCMaterial() {
		return this.cMaterial;
	}

	/**
	 * c_crisis_resistance を設定します.
	 * 
	 * @param cCrisisResistance
	 *            c_crisis_resistance
	 */
	public void setCCrisisResistance(Integer cCrisisResistance) {
		this.cCrisisResistance = cCrisisResistance;
	}

	/**
	 * c_crisis_resistance を取得します.
	 * 
	 * @return c_crisis_resistance
	 */
	public Integer getCCrisisResistance() {
		return this.cCrisisResistance;
	}

	/**
	 * c_independence を設定します.
	 * 
	 * @param cIndependence
	 *            c_independence
	 */
	public void setCIndependence(Integer cIndependence) {
		this.cIndependence = cIndependence;
	}

	/**
	 * c_independence を取得します.
	 * 
	 * @return c_independence
	 */
	public Integer getCIndependence() {
		return this.cIndependence;
	}

	/**
	 * c_control を設定します.
	 * 
	 * @param cControl
	 *            c_control
	 */
	public void setCControl(Integer cControl) {
		this.cControl = cControl;
	}

	/**
	 * c_control を取得します.
	 * 
	 * @return c_control
	 */
	public Integer getCControl() {
		return this.cControl;
	}

	/**
	 * c_workethic を設定します.
	 * 
	 * @param cWorkethic
	 *            c_workethic
	 */
	public void setCWorkethic(Integer cWorkethic) {
		this.cWorkethic = cWorkethic;
	}

	/**
	 * c_workethic を取得します.
	 * 
	 * @return c_workethic
	 */
	public Integer getCWorkethic() {
		return this.cWorkethic;
	}

	/**
	 * c_active を設定します.
	 * 
	 * @param cActive
	 *            c_active
	 */
	public void setCActive(Integer cActive) {
		this.cActive = cActive;
	}

	/**
	 * c_active を取得します.
	 * 
	 * @return c_active
	 */
	public Integer getCActive() {
		return this.cActive;
	}

	/**
	 * c_enthusiasm を設定します.
	 * 
	 * @param cEnthusiasm
	 *            c_enthusiasm
	 */
	public void setCEnthusiasm(Integer cEnthusiasm) {
		this.cEnthusiasm = cEnthusiasm;
	}

	/**
	 * c_enthusiasm を取得します.
	 * 
	 * @return c_enthusiasm
	 */
	public Integer getCEnthusiasm() {
		return this.cEnthusiasm;
	}

	/**
	 * c_perseverance を設定します.
	 * 
	 * @param cPerseverance
	 *            c_perseverance
	 */
	public void setCPerseverance(Integer cPerseverance) {
		this.cPerseverance = cPerseverance;
	}

	/**
	 * c_perseverance を取得します.
	 * 
	 * @return c_perseverance
	 */
	public Integer getCPerseverance() {
		return this.cPerseverance;
	}

	/**
	 * c_responsibility2 を設定します.
	 * 
	 * @param cResponsibility2
	 *            c_responsibility2
	 */
	public void setCResponsibility2(Integer cResponsibility2) {
		this.cResponsibility2 = cResponsibility2;
	}

	/**
	 * c_responsibility2 を取得します.
	 * 
	 * @return c_responsibility2
	 */
	public Integer getCResponsibility2() {
		return this.cResponsibility2;
	}

	/**
	 * c_decisive を設定します.
	 * 
	 * @param cDecisive
	 *            c_decisive
	 */
	public void setCDecisive(Integer cDecisive) {
		this.cDecisive = cDecisive;
	}

	/**
	 * c_decisive を取得します.
	 * 
	 * @return c_decisive
	 */
	public Integer getCDecisive() {
		return this.cDecisive;
	}

	/**
	 * c_leadership2 を設定します.
	 * 
	 * @param cLeadership2
	 *            c_leadership2
	 */
	public void setCLeadership2(Integer cLeadership2) {
		this.cLeadership2 = cLeadership2;
	}

	/**
	 * c_leadership2 を取得します.
	 * 
	 * @return c_leadership2
	 */
	public Integer getCLeadership2() {
		return this.cLeadership2;
	}

	/**
	 * c_leader を設定します.
	 * 
	 * @param cLeader
	 *            c_leader
	 */
	public void setCLeader(Integer cLeader) {
		this.cLeader = cLeader;
	}

	/**
	 * c_leader を取得します.
	 * 
	 * @return c_leader
	 */
	public Integer getCLeader() {
		return this.cLeader;
	}

	/**
	 * c_selftrust を設定します.
	 * 
	 * @param cSelftrust
	 *            c_selftrust
	 */
	public void setCSelftrust(Integer cSelftrust) {
		this.cSelftrust = cSelftrust;
	}

	/**
	 * c_selftrust を取得します.
	 * 
	 * @return c_selftrust
	 */
	public Integer getCSelftrust() {
		return this.cSelftrust;
	}

	/**
	 * c_adjustment を設定します.
	 * 
	 * @param cAdjustment
	 *            c_adjustment
	 */
	public void setCAdjustment(Integer cAdjustment) {
		this.cAdjustment = cAdjustment;
	}

	/**
	 * c_adjustment を取得します.
	 * 
	 * @return c_adjustment
	 */
	public Integer getCAdjustment() {
		return this.cAdjustment;
	}

	/**
	 * c_negotiation を設定します.
	 * 
	 * @param cNegotiation
	 *            c_negotiation
	 */
	public void setCNegotiation(Integer cNegotiation) {
		this.cNegotiation = cNegotiation;
	}

	/**
	 * c_negotiation を取得します.
	 * 
	 * @return c_negotiation
	 */
	public Integer getCNegotiation() {
		return this.cNegotiation;
	}

	/**
	 * c_innovative を設定します.
	 * 
	 * @param cInnovative
	 *            c_innovative
	 */
	public void setCInnovative(Integer cInnovative) {
		this.cInnovative = cInnovative;
	}

	/**
	 * c_innovative を取得します.
	 * 
	 * @return c_innovative
	 */
	public Integer getCInnovative() {
		return this.cInnovative;
	}

	/**
	 * c_analysis を設定します.
	 * 
	 * @param cAnalysis
	 *            c_analysis
	 */
	public void setCAnalysis(Integer cAnalysis) {
		this.cAnalysis = cAnalysis;
	}

	/**
	 * c_analysis を取得します.
	 * 
	 * @return c_analysis
	 */
	public Integer getCAnalysis() {
		return this.cAnalysis;
	}

	/**
	 * c_Insight を設定します.
	 * 
	 * @param cInsight
	 *            c_Insight
	 */
	public void setCInsight(Integer cInsight) {
		this.cInsight = cInsight;
	}

	/**
	 * c_Insight を取得します.
	 * 
	 * @return c_Insight
	 */
	public Integer getCInsight() {
		return this.cInsight;
	}

	/**
	 * c_planning を設定します.
	 * 
	 * @param cPlanning
	 *            c_planning
	 */
	public void setCPlanning(Integer cPlanning) {
		this.cPlanning = cPlanning;
	}

	/**
	 * c_planning を取得します.
	 * 
	 * @return c_planning
	 */
	public Integer getCPlanning() {
		return this.cPlanning;
	}

	/**
	 * c_expertise を設定します.
	 * 
	 * @param cExpertise
	 *            c_expertise
	 */
	public void setCExpertise(Integer cExpertise) {
		this.cExpertise = cExpertise;
	}

	/**
	 * c_expertise を取得します.
	 * 
	 * @return c_expertise
	 */
	public Integer getCExpertise() {
		return this.cExpertise;
	}

	/**
	 * c_utilization を設定します.
	 * 
	 * @param cUtilization
	 *            c_utilization
	 */
	public void setCUtilization(Integer cUtilization) {
		this.cUtilization = cUtilization;
	}

	/**
	 * c_utilization を取得します.
	 * 
	 * @return c_utilization
	 */
	public Integer getCUtilization() {
		return this.cUtilization;
	}

	/**
	 * c_general を設定します.
	 * 
	 * @param cGeneral
	 *            c_general
	 */
	public void setCGeneral(Integer cGeneral) {
		this.cGeneral = cGeneral;
	}

	/**
	 * c_general を取得します.
	 * 
	 * @return c_general
	 */
	public Integer getCGeneral() {
		return this.cGeneral;
	}

	/**
	 * c_mental を設定します.
	 * 
	 * @param cMental
	 *            c_mental
	 */
	public void setCMental(Integer cMental) {
		this.cMental = cMental;
	}

	/**
	 * c_mental を取得します.
	 * 
	 * @return c_mental
	 */
	public Integer getCMental() {
		return this.cMental;
	}

	/**
	 * c_legwaist を設定します.
	 * 
	 * @param cLegwaist
	 *            c_legwaist
	 */
	public void setCLegwaist(Integer cLegwaist) {
		this.cLegwaist = cLegwaist;
	}

	/**
	 * c_legwaist を取得します.
	 * 
	 * @return c_legwaist
	 */
	public Integer getCLegwaist() {
		return this.cLegwaist;
	}

	/**
	 * c_concentration を設定します.
	 * 
	 * @param cConcentration
	 *            c_concentration
	 */
	public void setCConcentration(Integer cConcentration) {
		this.cConcentration = cConcentration;
	}

	/**
	 * c_concentration を取得します.
	 * 
	 * @return c_concentration
	 */
	public Integer getCConcentration() {
		return this.cConcentration;
	}

	/**
	 * c_standardization を設定します.
	 * 
	 * @param cStandardization
	 *            c_standardization
	 */
	public void setCStandardization(Integer cStandardization) {
		this.cStandardization = cStandardization;
	}

	/**
	 * c_standardization を取得します.
	 * 
	 * @return c_standardization
	 */
	public Integer getCStandardization() {
		return this.cStandardization;
	}

	/**
	 * c_range を設定します.
	 * 
	 * @param cRange
	 *            c_range
	 */
	public void setCRange(Integer cRange) {
		this.cRange = cRange;
	}

	/**
	 * c_range を取得します.
	 * 
	 * @return c_range
	 */
	public Integer getCRange() {
		return this.cRange;
	}

	/**
	 * c_established を設定します.
	 * 
	 * @param cEstablished
	 *            c_established
	 */
	public void setCEstablished(Integer cEstablished) {
		this.cEstablished = cEstablished;
	}

	/**
	 * c_established を取得します.
	 * 
	 * @return c_established
	 */
	public Integer getCEstablished() {
		return this.cEstablished;
	}

	/**
	 * c_typejudge を設定します.
	 * 
	 * @param cTypejudge
	 *            c_typejudge
	 */
	public void setCTypejudge(String cTypejudge) {
		this.cTypejudge = cTypejudge;
	}

	/**
	 * c_typejudge を取得します.
	 * 
	 * @return c_typejudge
	 */
	public String getCTypejudge() {
		return this.cTypejudge;
	}

	/**
	 * 進路決定テーブル 一覧を設定します.
	 * 
	 * @param careerReportTblSet
	 *            進路決定テーブル 一覧
	 */
	public void setCareerReportTblSet(Set<CareerReportTbl> careerReportTblSet) {
		this.careerReportTblSet = careerReportTblSet;
	}

	/**
	 * 進路決定テーブル を追加します.
	 * 
	 * @param careerReportTbl
	 *            進路決定テーブル
	 */
	public void addCareerReportTbl(CareerReportTbl careerReportTbl) {
		this.careerReportTblSet.add(careerReportTbl);
	}

	/**
	 * 進路決定テーブル 一覧を取得します.
	 * 
	 * @return 進路決定テーブル 一覧
	 */
	public Set<CareerReportTbl> getCareerReportTblSet() {
		return this.careerReportTblSet;
	}

	/**
	 * 就職テーブル 一覧を設定します.
	 * 
	 * @param jobHuntingTblSet
	 *            就職テーブル 一覧
	 */
	public void setJobHuntingTblSet(Set<JobHuntingTbl> jobHuntingTblSet) {
		this.jobHuntingTblSet = jobHuntingTblSet;
	}

	/**
	 * 就職テーブル を追加します.
	 * 
	 * @param jobHuntingTbl
	 *            就職テーブル
	 */
	public void addJobHuntingTbl(JobHuntingTbl jobHuntingTbl) {
		this.jobHuntingTblSet.add(jobHuntingTbl);
	}

	/**
	 * 就職テーブル 一覧を取得します.
	 * 
	 * @return 就職テーブル 一覧
	 */
	public Set<JobHuntingTbl> getJobHuntingTblSet() {
		return this.jobHuntingTblSet;
	}

	/**
	 * 個別メッセージテーブル 一覧を設定します.
	 * 
	 * @param messageTblSet
	 *            個別メッセージテーブル 一覧
	 */
	public void setMessageTblSet(Set<MessageTbl> messageTblSet) {
		this.messageTblSet = messageTblSet;
	}

	/**
	 * 個別メッセージテーブル を追加します.
	 * 
	 * @param messageTbl
	 *            個別メッセージテーブル
	 */
	public void addMessageTbl(MessageTbl messageTbl) {
		this.messageTblSet.add(messageTbl);
	}

	/**
	 * 個別メッセージテーブル 一覧を取得します.
	 * 
	 * @return 個別メッセージテーブル 一覧
	 */
	public Set<MessageTbl> getMessageTblSet() {
		return this.messageTblSet;
	}

	/**
	 * 未読テーブル 一覧を設定します.
	 * 
	 * @param unreadTblSet
	 *            未読テーブル 一覧
	 */
	public void setUnreadTblSet(Set<UnreadTbl> unreadTblSet) {
		this.unreadTblSet = unreadTblSet;
	}

	/**
	 * 未読テーブル を追加します.
	 * 
	 * @param unreadTbl
	 *            未読テーブル
	 */
	public void addUnreadTbl(UnreadTbl unreadTbl) {
		this.unreadTblSet.add(unreadTbl);
	}

	/**
	 * 未読テーブル 一覧を取得します.
	 * 
	 * @return 未読テーブル 一覧
	 */
	public Set<UnreadTbl> getUnreadTblSet() {
		return this.unreadTblSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((studentId == null) ? 0 : studentId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		StudentTbl other = (StudentTbl) obj;
		if (studentId == null) {
			if (other.studentId != null) {
				return false;
			}
		} else if (!studentId.equals(other.studentId)) {
			return false;
		}
		return true;
	}

}
