package jp.ac.asojuku.jobhuntingsystem.entity;

import java.io.Serializable;

/**
 * 学生職種テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class StudentIndustryTbl implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** si_id. */
	private Integer siId;

	/** 学生テーブル. */
	private StudentTbl studentTbl;

	/** 業種テーブル. */
	private IndustrykindTbl industrykindTbl;

	/**
	 * コンストラクタ.
	 */
	public StudentIndustryTbl() {
	}

	/**
	 * si_id を設定します.
	 * 
	 * @param siId
	 *            si_id
	 */
	public void setSiId(Integer siId) {
		this.siId = siId;
	}

	/**
	 * si_id を取得します.
	 * 
	 * @return si_id
	 */
	public Integer getSiId() {
		return this.siId;
	}

	/**
	 * 学生テーブル を設定します.
	 * 
	 * @param studentTbl
	 *            学生テーブル
	 */
	public void setStudentTbl(StudentTbl studentTbl) {
		this.studentTbl = studentTbl;
	}

	/**
	 * 学生テーブル を取得します.
	 * 
	 * @return 学生テーブル
	 */
	public StudentTbl getStudentTbl() {
		return this.studentTbl;
	}

	/**
	 * 業種テーブル を設定します.
	 * 
	 * @param industrykindTbl
	 *            業種テーブル
	 */
	public void setIndustrykindTbl(IndustrykindTbl industrykindTbl) {
		this.industrykindTbl = industrykindTbl;
	}

	/**
	 * 業種テーブル を取得します.
	 * 
	 * @return 業種テーブル
	 */
	public IndustrykindTbl getIndustrykindTbl() {
		return this.industrykindTbl;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((siId == null) ? 0 : siId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		StudentIndustryTbl other = (StudentIndustryTbl) obj;
		if (siId == null) {
			if (other.siId != null) {
				return false;
			}
		} else if (!siId.equals(other.siId)) {
			return false;
		}
		return true;
	}

}
