package jp.ac.asojuku.jobhuntingsystem.entity;

import java.io.Serializable;

/**
 * 未読テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class UnreadTbl implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** unread_id. */
	private Integer unreadId;

	/** 学生テーブル. */
	private StudentTbl studentTbl;

	/** お知らせテーブル. */
	private InfoTbl infoTbl;

	/**
	 * コンストラクタ.
	 */
	public UnreadTbl() {
	}

	/**
	 * unread_id を設定します.
	 * 
	 * @param unreadId
	 *            unread_id
	 */
	public void setUnreadId(Integer unreadId) {
		this.unreadId = unreadId;
	}

	/**
	 * unread_id を取得します.
	 * 
	 * @return unread_id
	 */
	public Integer getUnreadId() {
		return this.unreadId;
	}

	/**
	 * 学生テーブル を設定します.
	 * 
	 * @param studentTbl
	 *            学生テーブル
	 */
	public void setStudentTbl(StudentTbl studentTbl) {
		this.studentTbl = studentTbl;
	}

	/**
	 * 学生テーブル を取得します.
	 * 
	 * @return 学生テーブル
	 */
	public StudentTbl getStudentTbl() {
		return this.studentTbl;
	}

	/**
	 * お知らせテーブル を設定します.
	 * 
	 * @param infoTbl
	 *            お知らせテーブル
	 */
	public void setInfoTbl(InfoTbl infoTbl) {
		this.infoTbl = infoTbl;
	}

	/**
	 * お知らせテーブル を取得します.
	 * 
	 * @return お知らせテーブル
	 */
	public InfoTbl getInfoTbl() {
		return this.infoTbl;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((unreadId == null) ? 0 : unreadId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		UnreadTbl other = (UnreadTbl) obj;
		if (unreadId == null) {
			if (other.unreadId != null) {
				return false;
			}
		} else if (!unreadId.equals(other.unreadId)) {
			return false;
		}
		return true;
	}

}
