package jp.ac.asojuku.jobhuntingsystem.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import lombok.Data;

/**
 * 学科テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="class_tbl")
public class ClassEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** class_id. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer classId;

	/** name. */
	private String name;

	/** 学科テーブル. */
	private Integer departmentId;
	@OneToOne
    @JoinColumn(name="departmentId",insertable=false ,updatable=false)
	private DepartmentEntity departmentTbl;

	/** 管理者テーブル. */
	private Integer adminId;
	@OneToOne
    @JoinColumn(name="adminId",insertable=false ,updatable=false)
	private AdminEntity adminTbl;


}
