package jp.ac.asojuku.jobhuntingsystem.entity;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import lombok.Data;

/**
 * 企業業種テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="company_industry")
public class CompanyIndustry implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer ciId;

	/** 企業テーブル. */
	@OneToOne
    @JoinColumn(name="companyId",insertable=false ,updatable=false)
	private CompanyEntity companyTbl;

	/** 業種テーブル. */
	@OneToOne
    @JoinColumn(name="industrykindId",insertable=false ,updatable=false)
	private IndustrykindTbl industrykindTbl;


}
