package jp.ac.asojuku.jobhuntingsystem.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import lombok.Data;

/**
 * 業種テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="Industrykind_tbl")
public class IndustrykindTbl implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** industrykind_id. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer industrykindId;

	/** name. */
	private String name;

	/** 業界マスタ. */
	private Integer industryId;
	@ManyToOne
    @JoinColumn(name="industryId",insertable=false ,updatable=false)
	private IndustryEntity industryTbl;




}
