package jp.ac.asojuku.jobhuntingsystem.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import lombok.Data;

/**
 * 業界マスタ モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="industry_tbl")
public class IndustryEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** industry_id. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer industryId;

	/** name. */
	private String name;

	/** 業種テーブル 一覧. */
	@OneToMany(fetch = FetchType.LAZY)
    @JoinColumn(name="industryId")
	private List<IndustrykindTbl> industrykindTbl;


}
