package jp.ac.asojuku.jobhuntingsystem.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import lombok.Data;

/**
 * 就職テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="job_hunting_tbl")
public class JobHuntingEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** job_hunting_id. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer jobHuntingId;

	/** status. */
	private Integer status;

	/** step_start_datetime. */
	private Date stepStartDatetime;

	/** イベントテーブル. */
	private Integer eventId;
	@ManyToOne
    @JoinColumn(name="eventId",insertable=false ,updatable=false)
	private EventEntity eventTbl;

	/** need_report. */
	private Integer needReport;

	/** 学生テーブル. */
	private Integer studentId;
	@OneToOne
    @JoinColumn(name="studentId",insertable=false ,updatable=false)
	private StudentEntity studentTbl;

	/** onbehalf_flg. */
	private Integer onbehalfFlg;



}
