package jp.ac.asojuku.jobhuntingsystem.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * 就職活動状況マスタ モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="jobhunting_status_tbl")
public class JobhuntingStatusEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** jobhunting_status_id. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer jobhuntingStatusId;

	/** name. */
	private String name;


}
