package jp.ac.asojuku.jobhuntingsystem.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * 求人タイプテーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="recrutiment_type_tbl")
public class RecrutimentTypeEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** recrutiment_type_id. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer recrutimentTypeId;

	/** name. */
	private String name;


	/**
	 * コンストラクタ.
	 */
	public RecrutimentTypeEntity() {
	}


}
