package jp.ac.asojuku.jobhuntingsystem.entity;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import lombok.Data;

/**
 * 報告書 モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="report_tbl")
public class ReportEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** report_id. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer reportId;

	/** 就職活動詳細テーブル. */
	@OneToOne
    @JoinColumn(name="jobHuntingId",insertable=false ,updatable=false)
	private JobHuntingEntity jobHuntingTbl;

}
