package jp.ac.asojuku.jobhuntingsystem.entity;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import lombok.Data;

/**
 * 学生職種テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="student_industry_tbl")
public class StudentIndustryEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** si_id. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer siId;

	/** 学生テーブル. */
	private Integer studentId;

	@OneToOne
    @JoinColumn(name="studentId",insertable=false ,updatable=false)
	private StudentEntity studentTbl;

	/** 業種テーブル. */
	private Integer industrykindId;

	@OneToOne
    @JoinColumn(name="industrykindId",insertable=false ,updatable=false)
	private IndustrykindEntity industrykindTbl;


}
